### ISSUE TITLE
Replace the assets images with images from the OFF server

### ISSUE THREAD

**Issue by MohamedFBoussaid** [openfoodfacts/openfoodfacts-dart#101]
The assets images on the package are only used for the tests, and this is raising the package memory. 
As I solution we can replace those files with "online" images that can be called while the tests are running.

**Comment by peterwvj** [comment]
Hi @MohamedFBoussaid would it be possible to just add these images in a `test_resources` folder as described here https://stackoverflow.com/questions/45780255/flutter-how-to-load-file-for-testing

If I look `pubspec.yaml` it seems like only `assets/json/` is bundles as an asset so I'm not sure the images are ever bundled.

But maybe I'm missing something.

```
...
flutter:
  assets:
    - assets/json/

```

**Comment by MohamedFBoussaid** [comment]
@peterwvj yeah sure I can try that, but I am not sure if this will solve the issue of described by @monsieurtanuki [here](https://github.com/openfoodfacts/openfoodfacts-dart/pull/85#issuecomment-778601433). I forget to mention in the issue descirption that this is not only for the package size, but also to support the web in order to improve the package score on pub.dev

**Comment by monsieurtanuki** [comment]
@MohamedFBoussaid Could be worth trying what @peterwvj's link suggest, as long as the asset files are kept in the test area and not part of the library delivered to the developers.
I don't think we should care about web or not web *in the tests* either, as long as the "main" library handle both cases.

**Comment by MohamedFBoussaid** [comment]
tests updated.
