### ISSUE TITLE
Add support for the new "Image Refresh" API

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-dart#104]
Add support for the new "Image Refresh" API

Ensure we can request photo updates for select products to users for images which should be taken or re-taken (because they are too old, or possibly too small / blurry).

https://fr.openfoodfacts.org/api/v0/produit/3483130043180/beurre-cru-a-la-baratte-les-petites-laiteries?fields=images_to_update_fr

It returns a hash of image types + language code (only for the requested language code which should be the language of the app). The value is 0 for images we don't have, or the age of the image (in seconds) for apps that want to add some context like `"Our photo of the ingredients is 14 months old, could you take a new one?"`.

### Sample API response
```
product: {
images_to_update_fr: {
packaging_fr: 0,
front_fr: 83734290,
ingredients_fr: 83734290
}
},
```
- [ ] Possible languages (we probably already have that in the package): https://static.openfoodfacts.org/data/taxonomies/languages.json
- [ ] Possible fields (front, ingredients, nutrition, packaging)

### Pseudo code to use it in an app
for field in images_to_update_fr:
if field.value=0 
      verb = "take" 
else:
      verb = "refresh"
field_name = field.split.before("_")
field_language = field.split.after("_")
button_text = fetch_button_text(field_name, field_language, verb)

#### verb (pick the right one based on the verb)
"Take %s picture"
"Refresh %s picture"
#### field_name
"ingredients"
"front"
"nutrition"
"packaging"

### Optional - mention how old the image is

How to convert seconds in human readable format: 83734290 = 2 years and 7 months (example routine to convert) - https://stackoverflow.com/questions/29681328/convert-seconds-into-years-months-weeks-hours-minutes-and-seconds

### Send the right query based on the initial field in images_to_update_fr
- Do not use the computed values in the pseudo code
- Probably refactor the methods we currently have to pass the field name, and make it future proof if we want to add new image fields.

(adapted from the original issue @ https://github.com/openfoodfacts/api-documentation/issues/15 )

**Comment by monsieurtanuki** [comment]
@teolemon The "image refresh" API is now supported, as a brand new product field.
I don't know how close we are currently to what you had in mind; don't hesitate to close this issue or to give additional info about the expected result.

**Comment by teolemon** [comment]
thats seems good, we can probably implement the rest in Smoothie

**Comment by teolemon** [comment]
https://github.com/openfoodfacts/openfoodfacts-server/issues/9226

**Comment by teolemon** [comment]
I believe we can close this

**Comment by monsieurtanuki** [comment]
@teolemon Not sure which method we're using in Smoothie (image_updates_fr or uploaded_ts of the root image), but both are supported in off-dart.
