### ISSUE TITLE
Add support for list queries

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-dart#105]
Add support for list queries
Example
https://world.openfoodfacts.dev/products/8024884500403,3263855093192,3045320001570,3021762383344,4008400402222,3330720237255,3608580823513,3700278403936,3302747010029,3608580823490,3250391660995,3760020506605,8722700202387,3330720237330,3535800940005,20000691,3270190127512.json?fields=code,product_name

**Comment by monsieurtanuki** [comment]
Done in #182.
