### ISSUE TITLE
Simplify the definition of search queries, remove some unneeded code

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-dart#107]
There are a few things that could be simplified / removed from the definition of search queries:

e.g.

      var parameters = <Parameter>[
        const OutputFormat(format: Format.JSON),
        const Page(page: 5),
        const PageSize(size: 10),
        const SearchSimple(active: true),
        const SortBy(option: SortOption.PRODUCT_NAME),
        const TagFilter(
            tagType: "categories",
            contains: true,
            tagName: "breakfast_cereals"),
        const TagFilter(
            tagType: "nutrition_grades", contains: true, tagName: "A")
      ];

const OutputFormat(format: Format.JSON)  --> we just need JSON, the other formats like XML or JSONP are not needed, they are only available for clients that do not understand JSON

const SearchSimple(active: true),  --> this has absolutely no effect, it can be removed

I think we should remove all associated code. That means it would be a breaking change, and clients would have to remove it.

**Comment by monsieurtanuki** [comment]
Fixed by #180.
