### ISSUE TITLE
Null safety

### ISSUE THREAD

**Issue by M123-dev** [openfoodfacts/openfoodfacts-dart#113]
Big news. Flutter 2.0.0 has just entered the stable channel.
There are a lot of big changes. 💯 
Here all the [release notes](https://flutter.dev/docs/development/tools/sdk/release-notes) and the [annauncment](https://medium.com/flutter/whats-new-in-flutter-2-0-fe8e95ecc65).

The most important thing for the package, null safety, is now also stable. As I already noted in #90 , all packages we use are ready for null safety. That means we are now ready to upgrade.

**Comment by MohamedFBoussaid** [comment]
@M123-dev The show was interesting, I have already give it a try during the show to migrate to null-safety, but it seems harder then showed.  I will give it a second try to see how it goes. 
But they did great job with the dart migrate tool
https://www.youtube.com/watch?v=bvq7wbn4VAA&ab_channel=Flutter

**Comment by M123-dev** [comment]
@MohamedFBoussaid, how did your second try went

**Comment by MohamedFBoussaid** [comment]
@M123-dev I will check it tonight and let you know. Didn't get time during the week end

**Comment by M123-dev** [comment]
No need to rush

**Comment by MohamedFBoussaid** [comment]
@M123-dev I guess we are blocked till json_serializable release a null safety version 

Example of errors that I am getting.
[SEVERE] json_serializable:json_serializable on lib/model/Ingredient.dart (cached):
Generator cannot target libraries that have not been migrated to null-safety.

Let's wait for until build_runner and json_serializable  release null safety version

**Comment by M123-dev** [comment]
Where did this error occured?
I think this repo will take longer, but they said it should work. https://github.com/google/json_serializable.dart/issues/821#issuecomment-791787354

**Comment by MohamedFBoussaid** [comment]
I am getting it when I try to generate the g files using : 
flutter packages pub run  build_runner build lib --delete-conflicting-outputs

But even using this does not help, I am still getting the errors: 
flutter packages pub run --mode=--no-sound-null-safety  build_runner build lib --delete-conflicting-outputs

**Comment by stephanegigandet** [comment]
Same for me, I can't generate the g files using "flutter packages pub run build_runner build lib --delete-conflicting-outputs" , and I get this error: https://github.com/google/json_serializable.dart/issues/823

**Comment by M123-dev** [comment]
I am not a core contributor to the plugin. What are the g files for and in which step are they generated?
Is the error message incorrect or can we  just generation either after the migration or beforehand with an older version of build_runner

**Comment by stephanegigandet** [comment]
files like Product.g.dart are generated from Product.dart with the command "flutter packages pub run build_runner build lib --delete-conflicting-outputs"

I downgraded the packages locally in order to be able to generate the files, as suggested here: https://stackoverflow.com/questions/66477445/generator-cannot-target-libraries-that-have-not-been-migrated-to-null-safety

**Comment by peterwvj** [comment]
We had to migrate our own code in order to run build_runner. I did that with PR #119 which is still work-in-progress.

**Comment by peterwvj** [comment]
Now all tests pass with respect to the changes made as part of #119 which is now ready for review.
