### ISSUE TITLE
Add vegan and vegetarian status to the Ingredient class

### ISSUE THREAD

**Issue by blazern** [openfoodfacts/openfoodfacts-dart#125]
Hi! :)

When a product is requested from Rest API of OFF, the response contains vegan/vegetarian status for each ingredient of the product.
But the `Ingredient` class from Dart SDK doesn't include the veg-status for some reason.

It seems that adding the fields wouldn't be too hard as Ingredient extends JsonObject and is parsed automatically.

**Comment by peterwvj** [comment]
Thanks for reporting. Would you be willing to give it a try? :) Seems like a good first issue.

**Comment by MohamedFBoussaid** [comment]
Thanks @blazern for the contribution.

**Comment by peterwvj** [comment]
This was fixed with the PR so I'll go ahead and close it.
