### ISSUE TITLE
Add support for Autocompleting values

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-dart#131]
Getting suggestions for states
https://world.openfoodfacts.org/cgi/suggest.pl?lc=fr&tagtype=states&string=a

Getting suggestions for languages
https://world.openfoodfacts.org/cgi/suggest.pl?lc=fr&tagtype=languages&string=a

Getting suggestions for labels
https://world.openfoodfacts.org/cgi/suggest.pl?lc=fr&tagtype=labels&string=a

Getting suggestions for categories
https://world.openfoodfacts.org/cgi/suggest.pl?lc=fr&tagtype=categories&string=a

Getting suggestions for Countries
https://world.openfoodfacts.org/cgi/suggest.pl?lc=fr&tagtype=countries&string=f

Getting suggestions for ingredients 
https://world.openfoodfacts.org/cgi/suggest.pl?lc=fr&tagtype=ingredients&string=f

Getting suggestions for traces
https://world.openfoodfacts.org/cgi/suggest.pl?lc=fr&tagtype=traces&string=m

Getting suggestions for additives
https://world.openfoodfacts.org/cgi/suggest.pl?lc=fr&tagtype=additives&string=e

Getting suggestions for allergens
https://world.openfoodfacts.org/cgi/suggest.pl?lc=fr&tagtype=allergens&string=a

Getting suggestions for packager codes
https://world.openfoodfacts.org/cgi/suggest.pl?lc=en&tagtype=emb_codes&EM

**Comment by M123-dev** [comment]
Would be great for openfoodfacts/smooth-app/issues/147

**Comment by teolemon** [comment]
Also for a future addition mode.

**Comment by monsieurtanuki** [comment]
@M123-dev For https://github.com/openfoodfacts/smooth-app/issues/147 we would rather need something about "food" itself, I guess. And none of the suggestions is about food name.

**Comment by M123-dev** [comment]
@monsieurtanuki oh didn't noticed, I would ofc suggest that too if the api allows it

**Comment by MohamedFBoussaid** [comment]
@teolemon The changes were merged to master. 
Can we close this issue ?

**Comment by teolemon** [comment]
yes
