### ISSUE TITLE
Add support for Open Food Facts user creation

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-dart#133]
Abstract the HTML form we currently have to enable simple OFF account creation for apps.
https://github.com/openfoodfacts/openfoodfacts-androidapp/pull/3737

**Comment by M123-dev** [comment]
@teolemon, do you mean a custom OFF-dart widget or just to the background logic?

**Comment by teolemon** [comment]
The background logic would already be nice

**Comment by teolemon** [comment]
We can do the widget in smoothie (or keep it here, unsure if that's something possible in packages)

**Comment by M123-dev** [comment]
@teolemon, at the time the latest stable is a flutter and the latest beta is a dart/flutter package, but I think its managable to keep the dart support even with flutter functionality.

I am not able to find a documentation about creating or receving user data, is there any?
