### ISSUE TITLE
How to get plant-based spreads?

### ISSUE THREAD

**Issue by kiromousa** [openfoodfacts/openfoodfacts-dart#137]
How to get plant-based spreads in nutrition facts for each nutriment using open food facts dart package?

**Comment by kiromousa** [comment]
@MohamedFBoussaid can you maybe help, Please?

**Comment by MohamedFBoussaid** [comment]
@kiromousa what do you mean by plant-based ? Can you give an example from the [OFF API](https://world.openfoodfacts.org/files/api-documentation.html)

**Comment by kiromousa** [comment]
this what i mean!
https://drive.google.com/file/d/1j1ngNeesOMIQt_KEIV0_bsMounlCXfXO/view?usp=sharing

**Comment by MohamedFBoussaid** [comment]
I don't have permissions to access the link

**Comment by kiromousa** [comment]
i am Sorry!! you can see it here: https://ibb.co/NyVXdfH

Thanks Mohamed!!

**Comment by MohamedFBoussaid** [comment]
Ah no this is not implemented on the package!

**Comment by kiromousa** [comment]
Ah ok! Just to know, Could this be implemented in the next package update?
