### ISSUE TITLE
error while parsing ingredient percentage

### ISSUE THREAD

**Issue by Grumpf86** [openfoodfacts/openfoodfacts-dart#14]
the ingredient percentage attribute could not be mappend, cause double could not be parsed as int.

Steps to reproduce: start api_test_searchProducts.dart - search by keyword

`package:openfoodfacts/interface/JsonObject.dart 19:7   JsonObject.parseInt
package:openfoodfacts/model/Ingredient.g.dart 14:25    _$IngredientFromJson
package:openfoodfacts/model/Ingredient.dart 22:7       new Ingredient.fromJson
package:openfoodfacts/model/Product.g.dart 46:43       _$ProductFromJson.<fn>
dart:_internal                                         ListIterable.toList
package:openfoodfacts/model/Product.g.dart 47:11       _$ProductFromJson
package:openfoodfacts/model/Product.dart 99:7          new Product.fromJson
package:openfoodfacts/model/SearchResult.g.dart 17:40  _$SearchResultFromJson.<fn>
dart:_internal                                         ListIterable.toList
package:openfoodfacts/model/SearchResult.g.dart 18:11  _$SearchResultFromJson
package:openfoodfacts/model/SearchResult.dart 28:7     new SearchResult.fromJson
package:openfoodfacts/openfoodfacts.dart 149:31        OpenFoodAPIClient.searchProducts

type 'double' is not a subtype of type 'int'`

**Comment by tzehe** [comment]
I am facing the same issue. Setting it to double would fix the issue. Are there any objections against that? I am only using this project since today so maybe I misses something. Would be awesome if some maintainer could say something about that.

**Comment by Grumpf86** [comment]
parse as double seems to ignore int values for this example
https://world.openfoodfacts.org/api/v0/product/4388860154948.json

number of ingredients: 11
{text: Frischei, bold: true}
{text: Zucker, bold: false}
{text: Palmfett, bold: false}
{text: Weizenmehl, bold: true}
{text: Lupinenmehl, bold: true}
{text: Magermilchpulver, bold: true}
{text: Speisesalz, bold: false}
{text: Rapsöl, bold: false}
{text: Emulgator Lecithine, bold: false}
{text: natürliches Aroma, bold: false}
{text: Eier aus Bodenhaltung, bold: false}

**Comment by peterwvj** [comment]
I'm experiencing this as well. Any progress on this issue?

**Comment by peterwvj** [comment]
This issue seems to show up sporadically but often. How come is that? Is there a workaround?@Grumpf86

**Comment by Grumpf86** [comment]
I will try to fix it this week and make the mapping robust against JSON "type-safety".

If I remember this issue correctly, the underlying problem was the synchronization of "ingredient_text" and the "ingredient" objects. I will remove this fragile logic. A reliable mapping is not possible with the given data.

After the fix the result of "ingredients" wont have a name anymore. (cause the api is not providing it.) The ingredient object will only contain the OFF taxonomy identifier afterwards e.g.: "en:rice-noodles" instead of "Rice" or "Reis" or "Riz".

@peterwvj I use only the "ingredient_text" field for my personal app at the moment.

**Comment by Grumpf86** [comment]
To query the german api does not provide german text:
https://de.openfoodfacts.org/api/v0/product/737628064502.json

`{"has_sub_ingredients":"yes","percent_min":7.69230769230769,**"text":"Noodle"**,"rank":1,"percent_max":100,"id":"en:noodle"},`

**Comment by Grumpf86** [comment]
I fixed the error and just released a new version 0.3.3. containing that fix.
-> ingredient percentage will be parsed as double.

The ingredient objects still contain the text in the requested language, cause the server is providing this information now. :)
Notice: that the ingredient text may contain underscores for bold ingredients like "_water_"

**Comment by peterwvj** [comment]
Thanks a lot for looking into this. I'll try to upgrade the new version and give it a try :)

**Comment by peterwvj** [comment]
Hi @Grumpf86 after upgrading to 0.3.3 or 0.3.4 all my searches seem to break. Here's the stacktrace:

![search](https://user-images.githubusercontent.com/5388919/85871683-0c423400-b7cf-11ea-8051-3531a4536810.png)

```
exception
_CastError (type 'int' is not a subtype of type 'String' in type cast)
stacktrace
#0      _$ProductFromJson (package:openfoodfacts/model/Product.g.dart:39:47)
#1      new Product.fromJson (package:openfoodfacts/model/Product.dart:132:7)
#2      _$SearchResultFromJson.<anonymous closure> (package:openfoodfacts/model/SearchResult.g.dart:17:40)
#3      MappedListIterable.elementAt (dart:_internal/iterable.dart:417:31)
#4      ListIterable.toList (dart:_internal/iterable.dart:221:19)
#5      _$SearchResultFromJson (package:openfoodfacts/model/SearchResult.g.dart:18:11)
#6      new SearchResult.fromJson (package:openfoodfacts/model/SearchResult.dart:28:7)
#7      OpenFoodAPIClient.searchProducts (package:openfoodfacts/openfoodfacts.dart:167:31)
<asynchronous suspension>
#8      _SearchRouteState._search (package:fit_app/search.dart:43:35)
#9      _SearchRouteState.build.<anonymous closure> (package:fit_app/search.dart:77:29)
#10     EditableTextState._finalizeEditing (package:flutter/src/widgets/editable_text.dart:1380:25)
#11     EditableTextState.performAction (package:flutter/src/widgets/editable_text.dart:1283:9)
#12     TextInput._handleTextInputInvocation (package:flutter/src/services/text_input.dart:1070:36)
#13     MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:409:55)
#14     MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:377:54)
#15     _DefaultBinaryMessenger.handlePlatformMessage (package:flutter/src/services/binding.dart:199:33)
#16     _invoke3.<anonymous closure> (dart:ui/hooks.dart:290:15)
#17     _rootRun (dart:async/zone.dart:1184:13)
#18     _CustomZone.run (dart:async/zone.dart:1077:19)
#19     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
#20     _invoke3 (dart:ui/hooks.dart:289:10)
#21     _dispatchPlatformMessage (dart:ui/hooks.dart:164:5)
```

Here's the relevant part of the code I believe

```dart
    var parameters = <Parameter>[
      const OutputFormat(format: Format.JSON),
      const PageSize(size: 20),
      const SearchSimple(active: true),
      SearchTerms(terms: [_controller.text.trim()]),
    ];
    ProductSearchQueryConfiguration configuration =
        ProductSearchQueryConfiguration(
      parametersList: parameters,
      fields: [ProductField.ALL],
    );
    try {
      SearchResult result =
          await OpenFoodAPIClient.searchProducts(null, configuration);
      _streamController.add(result);
    } catch (exception, stacktrace) {
      print('Exception $exception');
      print('Stack trace $stacktrace');
    }
```
Hope this helps.

**Comment by Grumpf86** [comment]
Hey @peterwvj  thanks for the information :) 
Please use the version 0.3.3. meanwhile - it contains the ingredient percentage fix and the search tests succeed.

@PrimaelQuemerais something went wrong with version 0.3.4. there is a problem with the product search as Peter mentioned and I can confirm, the product search tests are failing for this version. 

I will open an issue.

**Comment by PrimaelQuemerais** [comment]
Oops sorry, I thought I ran all the tests.
I'll take a look into it

**Comment by peterwvj** [comment]
Thanks for the quick response. Yes, I can confirm that 0.3.3 works as expected.

**Comment by Grumpf86** [comment]
here is the issue: https://github.com/openfoodfacts/openfoodfacts-dart/issues/27

@PrimaelQuemerais no problem, I wish you success :)
