### ISSUE TITLE
no way to save a product with Dart SDK with `product_name_ru` or `ingredients_text_ru`

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-dart#151]
Reported on Slack by Danil @blazern 

- Seems like currently there's no way to save a product with Dart SDK with `product_name_ru` or `ingredients_text_ru` (only with `product_name` and `ingredients_text`).
- Which causes at least 2 problems:
-- It seems `product_name_en` is filled when `product_name` is filled, so Russian product names are written into `product_name_en` as if they're in English. For example: https://ru.openfoodfacts.org/продукт/4680015760456/
-- When user scans a barcode of a product which has its `product_name` in for example French, the user has no way to add a name in Russian because SDK doesn't support it.
- Would that be ok if I changed the SDK in a way that when a product is saved a language code can be used, and if it's used then its appended to each of the fields?
- So if a Russian user would save a new product, instead of `product_name` and `ingredients_text` fields `product_name_ru` and `ingredients_text_ru` would be sent to the Server.

Also, the same problem is present when a product is requested from the server - seems like currently there's no way to ask for Russian product name or ingredient list.

**Comment by blazern** [comment]
I think it might be a good idea to remove from the Product class all members with lang code postfixes (like `productNameEN`) and for each translatable member add a neighbor-member with `Translated` postfix (some such fields already exist, like `categoriesTagsTranslated`).
So when SDK is asked to get a product with for example Russian translation, both `productName` and `productNameTranslated` would be filled - the first field with the international name and the second with the Russian name.

To request custom number of translated fields when a product is requested, I'd add a `List<ProductField> translatedFields` member to `ProductQueryConfiguration` - all items from this list would be requested from the server with the language code being appended.
This way the SDK users would be able to request both translated and international fields, or just 1 type (translated/international), or neither.

Then, when a new product or a product update is being sent to the server, users of the SDK would be able to provide both international and local fields by filling the `Translated` members.

**Comment by blazern** [comment]
This issue can be closed now :)

**Comment by MohamedFBoussaid** [comment]
Issue fixed, closing it based on @blazern request
