### ISSUE TITLE
Multiple Model Classes missing?

### ISSUE THREAD

**Issue by Florian-Schoenherr** [openfoodfacts/openfoodfacts-dart#170]
using `openfoodfacts: ^0.3.15+3`
using flutter, `sdk: ">=2.12.0 <3.0.0"`

I get this (copied from one of the examples):
![missing ProductResult etc](https://user-images.githubusercontent.com/65456722/123411054-4f84dd80-d5b0-11eb-9d32-0dc1e823b892.png)

**Comment by Florian-Schoenherr** [comment]
just a guess: should I use the beta version instead? but it seems like the Model Classes should still be available?

**Comment by MohamedFBoussaid** [comment]
@Florian-Schoenherr thanks for opening the bug. Can you please share the class that have this problem. It is hard to check the issue with a screenshoot. 
You can use both version, the beta is the null-safety version, and the ^0.3.15+3 is a non null-safety version.

**Comment by Florian-Schoenherr** [comment]
![image](https://user-images.githubusercontent.com/65456722/123420830-5580bb80-d5bc-11eb-8dd7-96fabec8f227.png)
I only have these model classes available.
So there are quite a few missing, don't know which I would need.
Also `TestConstants` seems to be somewhere else?

**Comment by MohamedFBoussaid** [comment]
@Florian-Schoenherr  the [TestConstants is a helper used for the test](https://github.com/openfoodfacts/openfoodfacts-dart/blob/master/test/test_constants.dart), you should not use it in your code, but you can create your own helper based on the TestConstants

**Comment by blazern** [comment]
> @Florian-Schoenherr the TestConstants is a helper used for the test, you should not use it in your code, but you can create your own helper based on the TestConstants

In the provided screenshot Florian doesn't have most of the model classes that should be there... for example, the Product and Ingredient classes are gone.
Here's what my model folder looks like:
![image](https://user-images.githubusercontent.com/3338378/123427621-89b0a800-d5cd-11eb-9dba-d2e5ef402fd3.png)

**Comment by Florian-Schoenherr** [comment]
The github release also includes more stuff, maybe the dart pub dev release broke somehow?
Now that I deleted the `pub.dartlang.org\openfoodfacts-0.3.15+3` folder, it seems to work after running pub get again.

**Comment by MohamedFBoussaid** [comment]
Thanks @Florian-Schoenherr  for confirming that your problem is solved. 
I will close the issue, don't hesitate to come back to us in case of other issue.
