### ISSUE TITLE
Null safety and nullable product.barcode's ?

### ISSUE THREAD

**Issue by monsieurtanuki** [openfoodfacts/openfoodfacts-dart#172]
Unless there are legitimate cases when a product has no barcode, I suggest that we make a small change in https://github.com/openfoodfacts/openfoodfacts-dart/blob/master/lib/model/Product.dart:

`String barcode;`
instead of
`String? barcode;`

**Comment by peterwvj** [comment]
I'm not aware of any such products but the web site does offer an option to add products without barcodes
![image](https://user-images.githubusercontent.com/5388919/124021847-56668280-d9ec-11eb-959c-2f198647eb32.png)

**Comment by M123-dev** [comment]
I would say we change it that way, this would make the code much simpler since the barcode is often used as a kind of primary key.

Not directly related, but I know sometimes there are two products with the same barcode, how does this wrapper handle these cases?

**Comment by monsieurtanuki** [comment]
Perhaps a simple "orange" can be a product without a barcode.
Anyway, if there are cases of products with no barcode let's keep it nullable.
