### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by M123-dev** [openfoodfacts/openfoodfacts-dart#173]
The latest release on pub.dev is from the 30.03, lets make a new one.

Also, let's release the new version as latest and not as preversion. Smoothie uses the preversion, there are no bugs and null-safety has been mainstream for a while now.

**Comment by MohamedFBoussaid** [comment]
@M123-dev can I first please merge #169 (Missing documentation that I need to add) 
and I confirm that the perversion is stable and I didn't notice any issue comparing with the non null-safety version

**Comment by M123-dev** [comment]
No problem, this time makes no difference

**Comment by peterwvj** [comment]
I support this, #169 is merged.

**Comment by MohamedFBoussaid** [comment]
@peterwvj yes it is merged. 
Do you have the rights to release ? 
If yes, let's release a new version please.

**Comment by peterwvj** [comment]
Sure I can do the release. Will someone help with preparing the change log? I think a lot of things were changed since the last release but I haven't had much time to follow along.

**Comment by M123-dev** [comment]
@peterwvj, I have just gathered all the latest changes, and took the changelogs from the last preview releases. These can perhaps still be shortened.

I summarized the unimportant and internal changes and marked it as code so that no reference is made to each pr.
```
1.0.0
    Migrated SDK to null safety
    Updated test instructions in README.md
    Improved Github Action validation

1.0.1
    API method for searching products does not require a user being passed

1.0.2
    Added support for new fields (images URLs, vegan/vegetarian/from palm oil ingredients, categories, labels and packaging)
    Fixed test mode for addProductImage

1.1.0
    Renamed SendImage imageUrl parameter to imageUri as it is an Uri (breaking change)
    New product preferences and matching classes for personalized search (thanks to monsieurtanuki)
    Added missing values for IngredientsAnalysisTags, and renamed some values to match API names (breaking change)
    Fixed image upload and added PACKAGING image type

Since then:
    Mutliple minor changes: (teolemon, blazern, M123-dev, peterwvj, kant, MohamedFBoussaid)
    product_name_de, productNameEN, ... are deprecated use productNameTranslated instead (#152 by blazern) (breaking change)
    added the agribalyse field to Product.ecoscoreData (#160 by FredJul)
    added the support for the missing_data_warning field, which allows the user to know the ecoscore may be improved (#161 by FredJul)
    added support for user management (login: #167, user creation: #171 by M123-dev) 
    added [dart-doc documentation](https://openfoodfacts.github.io/openfoodfacts-dart/) (#168 by teolemon)
    added suggestion for states, languages, labels, categories, ...   (#169 by MohamedFBoussaid)
    
    
    

```

**Comment by peterwvj** [comment]
Thanks. Please have a look at #176
