### ISSUE TITLE
Add a Nutri-Score helper

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-dart#193]
Add a Nutri-Score helper to help apps get to the Nutri-Score instantly for their users

![image](https://user-images.githubusercontent.com/1689815/126289174-1217cbdb-59b7-447b-acb3-dbab67877859.png)

https://docs.google.com/document/d/1_Y3tdgB8w3VkL6tXgjzPVmkmFiXsBfy0UfS6Mg3MkLs/edit#heading=h.ftzz6kpf06gw

**Comment by monsieurtanuki** [comment]
Product improvements are now computed in `product.getProductImprovements()` (#217).
Beyond the `enum` values, I don't know how the translations are supposed to be integrated, and how.

**Comment by monsieurtanuki** [comment]
@teolemon Should we provide messages and translations, or are we done now thanks to `enum ProductImprovement` and `product.getProductImprovements()`?
Same question for #191.

**Comment by teolemon** [comment]
Translations can be done in smoothie @monsieurtanuki

**Comment by monsieurtanuki** [comment]
> Translations can be done in smoothie @monsieurtanuki

Then we can close this issue, can't we? And we should also ping both https://github.com/openfoodfacts/smooth-app/issues/518 and https://github.com/openfoodfacts/smooth-app/issues/519, shouldn't we?

**Comment by teolemon** [comment]
yes, it's fixed by the actions API
