### ISSUE TITLE
Replace obscure parameter ContainsAdditives with explicit WithoutAdditives

### ISSUE THREAD

**Issue by monsieurtanuki** [openfoodfacts/openfoodfacts-dart#194]
As far as I've understood things, the current use of `ContainsAdditives` is:
* `ContainsAdditives(filter: true)` means "without additives" (`'&additives=without'`)
* `ContainsAdditives(filter: false)` means "no additive filter at all" (`'&additives='`)

That's a bit confusing.

I suggest to deprecate `ContainsAdditives` and to create a new `Parameter` called `WithoutAdditives` (always `'&additives=without'`).

**Comment by stephanegigandet** [comment]
Sounds good to me.

**Comment by monsieurtanuki** [comment]
Done in #197.
