### ISSUE TITLE
New 1.3.0 release

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-dart#198]
I'm preparing a 1.3.0 release with the numerous changes from the last 2 weeks. It contains at least one breaking changed (renamed fields).

**Comment by monsieurtanuki** [comment]
@stephanegigandet Are there issues you would like to be dealt with before 1.3.0?

**Comment by stephanegigandet** [comment]
@monsieurtanuki I think all current open issues in https://github.com/openfoodfacts/openfoodfacts-dart/issues are for new independent feature requests (and not changes to existing features etc.), so there is nothing that should prevent a new release I think. Is there something you want to be in 1.3.0?

I think it's fine to do frequent releases, so if something else is added in the next few days, I don't have any issue with spending 15 minutes to release 1.3.1.

**Comment by monsieurtanuki** [comment]
@stephanegigandet No issue in particular, I was just asking. And I hope #90 will be solved as well (I couldn't find a way to compute the score before pub.dev).
