### ISSUE TITLE
Send user agent HTTP header without User parameter

### ISSUE THREAD

**Issue by christianfl** [openfoodfacts/openfoodfacts-dart#208]
Hello there!

I would like to conform to: https://wiki.openfoodfacts.org/API/Read and include my App name, version, etc. in the HTTP header when firing request against the API with this dart plugin.

However, I could not find any way to do this. I could only find this pull request but that indicates that one would have to include a user to the request: https://github.com/openfoodfacts/openfoodfacts-dart/pull/18

However, I would like to let the users of my app querying OFF without an account and in the future let them create unique accounts to add or change data. The current implementation on the other hand would let me think that I would have to create a global user for my app or am I mistaken?

Kind regards, Christian

**Comment by M123-dev** [comment]
Yeah, we should definitely provide a way to include this.

**Comment by monsieurtanuki** [comment]
I do think you can do that just by specifying `user.comment`, cf. [`HttpHelper`](https://github.com/openfoodfacts/openfoodfacts-dart/blob/master/lib/utils/HttpHelper.dart#L107-L110):
```dart
headers.addAll({
  'UserAgent':
      (user != null && user.comment != null) ? user.comment! : USER_AGENT
});
```

**Comment by christianfl** [comment]
@monsieurtanuki

So I didn't deep dive into the code yet but would the plugin allow me to create a user object with a random username and password just to specify the user agent in user.comment (odd naming scheme) or would the credentials be submitted (this was my guess).

If that's not possible however, creating an app-wide user which could actually login is not a good idea either...

**Comment by monsieurtanuki** [comment]
@christianfl Fair enough. I don't know what is planned regarding users.
