### ISSUE TITLE
Allow clients to pass the country as a parameter request while getting a product's details

### ISSUE THREAD

**Issue by jasmeet0817** [openfoodfacts/openfoodfacts-dart#216]
Currently openfoodfacts.dart queries "world.openfoodfacts.org" directly. See here: https://github.com/openfoodfacts/openfoodfacts-dart/blob/master/lib/openfoodfacts.dart#L66

The functionality of the app is quite different depending upon the country from where you are accessing it (specially when it comes to eco score details card display). So this should be configurable in the package. 

For testing, we should have a way of modifying the host url locally, to be able to test things without having to change the code.

**Comment by M123-dev** [comment]
I am going to add some kind of settings, which should be set once and used everywhere similar to the  User-Agent HTTP Header (#213)
Including:
- All currently hardcoded url hosts
- The QueryType
- A way to overwrite the cc field for debug purposes (to be able to see the eco score from other countries)

Should the User-Agent HTTP Header or maybe something other added as well

**Comment by monsieurtanuki** [comment]
@M123-dev I was thinking about `static` fields again, indeed like #213.
It should be the same for "country": we should not presume what the country is, but instead let the developer set the correct value (in a `static` field). If "country" is not set, it's going to be "https://world..." as it is now.

**Comment by jasmeet0817** [comment]
Are there a set of flags that can be overridden by developers locally? Or static fields that the developer could change in order to have different functional behavior in the app ? Usually we use flags for these things, but I guess static fields are fine for now. 

I would encourage adding all fields together in a file (settings.dart?) that a developer can modify to their liking, and clearly document each field and respective app behavior on it's modification. This is to ensure new developers are able to quickly find and modify settings.dart without having to look deep into the code.

**Comment by stephanegigandet** [comment]
Sorry I was on vacations and did not notice this issue before.

API queries should always go to the "world" subdomain, and language and country should be passed in the "cc" (country code) and "lc" (language code) parameter. Queries to subdomains [country code]-[language code].openfoodfacts.org do work today, but should not be encouraged.

**Comment by stephanegigandet** [comment]
Note that we already do have the "cc" parameter in product query configurations.
