### ISSUE TITLE
Create github releases for new releases

### ISSUE THREAD

**Issue by christianfl** [openfoodfacts/openfoodfacts-dart#225]
Hey guys! Just an idea, would love if you "implement" that but could also understand when it doesn't fit in your workflow.

As I'm still slowly developing an Open Source food tracker for Android I'm depending on this dart plugin. I would like to get informed for new releases so that I can test and use them for my app - So I'm subscribing to this and other plugins I'm using (with Watch > Custom > Releases and Security alerts) here on Github.

**Could you maybe think of adding new releases here on Github or is there any other possibility to get informed for new releases? I'm relatively new to Flutter, Dart, pub.dev and so on.**

Thanks in advance.
-Christian

**Comment by M123-dev** [comment]
I think that would be a good idea, but then I would directly suggest that we automate the entire release process. I'll have a look at that

**Comment by M123-dev** [comment]
@christianfl, just a quick reminder we published a new version with some big changes yesterday

**Comment by christianfl** [comment]
@M123-dev Hehe, thank you! This is some first class service. 🥇

**Comment by M123-dev** [comment]
Blocked by #250
