### ISSUE TITLE
Automated pub.dev auth problems

### ISSUE THREAD

**Issue by M123-dev** [openfoodfacts/openfoodfacts-dart#250]
I have automated the release of this package in #239 and #245, but there is still a problem. The release asks for a re-authentication. 

> Pub needs your authorization to upload packages on your behalf.
> In a web browser, go to https://accounts.google.com/o/oauth2/auth?[...]
> Then click "Allow access".
> Waiting for your authorization...

The link given there opens a google login page and then redirects to a local host which is not reachable because it runs on github actions.

**Comment by teolemon** [comment]
@stephanegigandet

**Comment by peterwvj** [comment]
I think you can run `pub publish` with the `-f` flag to avoid this.

```bash
λ flutter pub publish help
Command "publish" does not take any arguments.

Usage: pub publish [options]
-h, --help               Print this usage information.
-n, --dry-run            Validate but do not publish the package.
-f, --force              Publish without confirmation if there are no errors.
-C, --directory=<dir>    Run this in the directory<dir>.
```

**Comment by peterwvj** [comment]
Maybe you'll find this blog helpful https://medium.com/evenbit/publishing-dart-packages-with-github-actions-5240068a2f7d
