### ISSUE TITLE
search functionality broken (Json mapping)

### ISSUE THREAD

**Issue by Grumpf86** [openfoodfacts/openfoodfacts-dart#27]
all the search tests are failing with an error message like this:

`_CastError (type 'int' is not a subtype of type 'String' in type cast)
#0      _$ProductFromJson (package:openfoodfacts/model/Product.g.dart:39:47)
#1      new Product.fromJson (package:openfoodfacts/model/Product.dart:132:7)
#2      _$SearchResultFromJson.<anonymous closure> (package:openfoodfacts/model/SearchResult.g.dart:17:40)
#3      MappedListIterable.elementAt (dart:_internal/iterable.dart:417:31)
#4      ListIterable.toList (dart:_internal/iterable.dart:221:19)
#5      _$SearchResultFromJson (package:openfoodfacts/model/SearchResult.g.dart:18:11)
#6      new SearchResult.fromJson (package:openfoodfacts/model/SearchResult.dart:28:7)
#7      OpenFoodAPIClient.searchProducts (package:openfoodfacts/openfoodfacts.dart:167:31)
<asynchronous suspension>
#8      _SearchRouteState._search (package:fit_app/search.dart:43:35)
#9      _SearchRouteState.build.<anonymous closure> (package:fit_app/search.dart:77:29)
#10     EditableTextState._finalizeEditing (package:flutter/src/widgets/editable_text.dart:1380:25)
#11     EditableTextState.performAction (package:flutter/src/widgets/editable_text.dart:1283:9)
#12     TextInput._handleTextInputInvocation (package:flutter/src/services/text_input.dart:1070:36)
#13     MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:409:55)
#14     MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:377:54)
#15     _DefaultBinaryMessenger.handlePlatformMessage (package:flutter/src/services/binding.dart:199:33)
#16     _invoke3.<anonymous closure> (dart:ui/hooks.dart:290:15)
#17     _rootRun (dart:async/zone.dart:1184:13)
#18     _CustomZone.run (dart:async/zone.dart:1077:19)
#19     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
#20     _invoke3 (dart:ui/hooks.dart:289:10)
#21     _dispatchPlatformMessage (dart:ui/hooks.dart:164:5)
`

the problem may relate to version 0.3.4

**Comment by PrimaelQuemerais** [comment]
Fixed in 0.3.5
