### ISSUE TITLE
Get localized Open Food Facts product URI

### ISSUE THREAD

**Issue by monsieurtanuki** [openfoodfacts/openfoodfacts-dart#301]
**Is your feature request related to a problem? Please describe.**
Typical use case: in smoothie we want to open the OFF website on the given barcode page.

**Describe the solution you'd like**
Something like
```dart
static Uri getProductUri(
    final String barcode, {
    OpenFoodFactsLanguage? language,
    OpenFoodFactsCountry? country,
    });
```

**Describe alternatives you've considered**
Currently in smoothie we use `https://openfoodfacts.org/product/7300400481588/`
But here we don't specify the language or the country.
And if we do (`https://openfoodfacts.org/product/7300400481588/?lc=fr&cc=de`) that is not taken into account.

Is there an URI for a product, a language and a country, and if there is one, what is it?

**Comment by teolemon** [comment]
https://world.openfoodfacts.org/product/5701051301959/galletas-de-mantequilla-y-de-chocolate
https://world-fr.openfoodfacts.org/product/5701051301959/galletas-de-mantequilla-y-de-chocolate
https://world-es.openfoodfacts.org/product/5701051301959/galletas-de-mantequilla-y-de-chocolate
https://fr.openfoodfacts.org/product/5701051301959/galletas-de-mantequilla-y-de-chocolate
https://fr-es.openfoodfacts.org/product/5701051301959/galletas-de-mantequilla-y-de-chocolate

**Comment by monsieurtanuki** [comment]
That's perfect @teolemon, I'm working on it!

**Comment by monsieurtanuki** [comment]
Done in #302.
