### ISSUE TITLE
Add server-side photo rotation

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-dart#304]
### What
Add server-side photo rotation
https://openfoodfacts.github.io/api-documentation/#jump-4WRITERequests-Rotateaphoto

### Part of
- #218

**Comment by monsieurtanuki** [comment]
@teolemon Same "what is `imgid`?" question as in #305.

**Comment by teolemon** [comment]
imgid you can find in the request, it's a unique id assigned to uploaded images, regardless of whether they are selected or not. You apply a rotation to a raw image id, and you place it in id like front_fr (which is a selection)
https://world.openfoodfacts.org/api/v0/product/3017620422003.json?fields=images

**Comment by teolemon** [comment]
https://world.openfoodfacts.org/product/3760284870115/tiramisu-patissier
https://world.openfoodfacts.org/images/products/376/028/487/0115/1.jpg (1 is imgid)
https://world.openfoodfacts.org/images/products/376/028/487/0115/front_fr.8.full.jpg (front_fr is id, the 8 gets assigned automatically)

**Comment by monsieurtanuki** [comment]
Thank you @teolemon: the first step is to retrieve `imgid` from the product json into `ProductImage` - which was not the case so far.
I'm working on it...
