### ISSUE TITLE
Add server-side crop a photo

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-dart#305]
### What

- Server-side crop a photo 
- https://openfoodfacts.github.io/api-documentation/#jump-4WRITERequests-Cropaphoto

### Part of 
- #218

**Comment by monsieurtanuki** [comment]
@teolemon What is `imgid`?
![Capture d’écran 2021-12-04 à 16 15 04](https://user-images.githubusercontent.com/11576431/144714731-4dc821a8-cf0b-4696-8a79-0f56ac328ff9.png)

**Comment by teolemon** [comment]
imgid you can find in the request, it's a unique id assigned to uploaded images, regardless of whether they are selected or not. You apply a rotation to a raw image id, and you place it in id like front_fr (which is a selection)

**Comment by teolemon** [comment]
https://world.openfoodfacts.org/api/v0/product/3017620422003.json?fields=images

**Comment by monsieurtanuki** [comment]
There's probably something wrong in `product_image_crop.pl`, or in the way I expect the parameters to work:
* starting from https://static.openfoodfacts.net/images/products/425/075/220/0784/front_de.264.full.jpg (928x1248 pixels, 210019 bytes)
* and trying to crop it to (`x1=10&y1=10&x2=800&y2=500`) (top half) with https://world.openfoodfacts.net/cgi/product_image_crop.pl?code=4250752200784&id=front_de&imgid=4&x1=10&y1=10&x2=800&y2=500
* I get basically the same picture https://static.openfoodfacts.net/images/products/425/075/220/0784/front_de.265.400.jpg (297x400, 41902 bytes)

What's wrong?

**Comment by teolemon** [comment]
If you want to crop again an already cropped image like you do you need to start from the source image, get the current cropping cords if you want to expose them to the user, and apply the new crop Coors to the original image (1.jpg)

**Comment by monsieurtanuki** [comment]
I've tried from scratch on an existing product that did not have a `front_de` image.
* I added the `front_de` image (https://static.openfoodfacts.net/images/products/301/762/042/2003/front_de.345.full.jpg - it's just a test)
* then tried to crop it (https://world.openfoodfacts.net/cgi/product_image_crop.pl?code=3017620422003&id=front_de&imgid=108&x1=10&y1=10&x2=800&y2=500)
* still didn't crop at all (https://static.openfoodfacts.net/images/products/301/762/042/2003/front_de.346.400.jpg)

Btw how would I get the current cropping coords?

**Comment by teolemon** [comment]
https://world.openfoodfacts.net/cgi/product_image_crop.pl?code=3017620422003&id=1&imgid=front_fr&imgid=108&x1=10&y1=10&x2=800&y2=500)

**Comment by monsieurtanuki** [comment]
I found out what was missing: query parameter `coordinates_image_size=full`. With that parameter the crop coordinates are on the full uploaded image, not its "400-max" version.
I've just committed a code that works!
