### ISSUE TITLE
Add Server-side photo unselection 

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-dart#306]
### What

Add Server-side photo unselection 
https://openfoodfacts.github.io/api-documentation/#jump-4WRITERequests-Deselectingaphoto

### Part of 
- #218

**Comment by monsieurtanuki** [comment]
@teolemon Not very verbose, is it?
![Capture d’écran 2021-12-04 à 15 32 21](https://user-images.githubusercontent.com/11576431/144713265-426abfda-b4e1-4bec-b290-2af8dab87f30.png)

**Comment by teolemon** [comment]
thanks @monsieurtanuki , filed a documentation task at https://github.com/openfoodfacts/api-documentation/issues/49 with the proper route

**Comment by monsieurtanuki** [comment]
It looks like https://world.openfoodfacts.net/cgi/product_image_unselect.pl?code=4250752200784&id=ingredients_de from what I read in
* https://github.com/openfoodfacts/openfoodfacts-server/blob/main/cgi/product_image_unselect.pl
* https://github.com/openfoodfacts/openfoodfacts-server/blob/main/lib/ProductOpener/Images.pm

I'm about to PR.
