### ISSUE TITLE
api_addProductImage_test.dart failing

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-dart#318]
02:58 +63 -4: test/api_addProductImage_test.dart: OpenFoodAPIClient modify product image image crop [E]                                                                                                
  Expected: <50>
    Actual: <400>
  
  package:test_api                          expect
  test/api_addProductImage_test.dart 195:9  main.<fn>.<fn>
  

02:58 +63 -4: loading test/api_getTaxonomyLabels_test.dart

**Comment by monsieurtanuki** [comment]
@teolemon I've just tested again locally, it works.
In that test I crop an image into a [50,300] rectangle. It looks like my crop instruction has priority over the "400 max" rule.
Probably it's just a "bad luck" collision. There would be less collisions if distinct barcodes were used for "image rotation" and "image crop" tests.

**Comment by monsieurtanuki** [comment]
It looks ok now.
