### ISSUE TITLE
getKnowledgePanels does not access globalLanguages

### ISSUE THREAD

**Issue by M123-dev** [openfoodfacts/openfoodfacts-dart#345]
`getKnowledgePanels` sets `'lc': configuration.language!.code,` as queryParameters, we should add a computeLanguageCode(s) method to `AbstractQueryConfiguratios` so that this also checks back for globalLanguages

**Comment by monsieurtanuki** [comment]
@M123-dev I guess that should be part of a whole refactoring for version 2.0.0.

**Comment by monsieurtanuki** [comment]
From #371 `getKnowledgePanels` is deprecated - when using the more standard `getProduct` with `[ProductField.KNOWLEDGE_PANELS]` you don't have this issue anymore.
