### ISSUE TITLE
While running Widget tests on my app, OFF package is throwing an error

### ISSUE THREAD

**Issue by MohamedFBoussaid** [openfoodfacts/openfoodfacts-dart#346]
**Describe the bug**
While testing a widget that you OpenFoodAPIClient.getProduct(), I was getting this error : 

```
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following FormatException was thrown running a test:
Unexpected end of input (at character 1)

^

When the exception was thrown, this was the stack:
#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1405:5)
#1      _ChunkedJsonParser.close (dart:convert-patch/convert_patch.dart:523:7)
#2      _parseJson (dart:convert-patch/convert_patch.dart:41:10)
#3      JsonDecoder.convert (dart:convert/json.dart:506:36)
#4      JsonCodec.decode (dart:convert/json.dart:157:41)
#5      jsonDecode (dart:convert/json.dart:96:10)
#6      OpenFoodAPIClient.getProduct (package:openfoodfacts/openfoodfacts.dart:203:51)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)
```

The test description was:
  Update Product UI tests

**To Reproduce**
Create a test that will call a widget that use OpenFoodFactAPI.getProduct()

**Expected behavior**
No error should be thrown

**Screenshots**
If applicable, add screenshots to help explain your problem. Otherwise provide the error stacktraces.

**package information:**
Openfoodfacts package version: 1.7.0 (old version cause I have some dependency issues)

**Additional context**
@M123-dev @monsieurtanuki @peterwvj  I would like to get your opinion about the fix that I want to apply :

The error is here : 
```
    final jsonStr = _replaceQuotes(response.body);
    ProductResult result = ProductResult.fromJson(jsonDecode(jsonStr)); 
```
**No error will be thrown in the app code**, bcs in all case the response.body will never be null. But in the case of tests, Flutter will not make any http call, and it will give a null as response, to avoid having such errors on the widget tests I propose to change it to: 
   
```
 final jsonStr = _replaceQuotes(response.body);
    ProductResult result = jsonStr.isNotEmpty
        ? ProductResult.fromJson(jsonDecode(jsonStr))
        : ProductResult();
```

Test it on my Widget test after updating the package locally, and it didn't throw that error.

**Comment by peterwvj** [comment]
Hi @MohamedFBoussaid thanks for reporting. I'm using version 1.7.0 of the SDK in my app as well, and I don't experience the issue being reported here.

Are you certain that the problem is in the OFF SDK? If yes, can you write a unit test (that I can run on my machine) that produces the problem? Preferably a minimum example that produces the problem.

I'm also intrigued to know which version of the flutter you are using. Perhaps you could add the output of `flutter doctor -v` to the issue. I noticed that the error is raised in Dart SDK code.

**Comment by MohamedFBoussaid** [comment]
Hi @peterwvj 
Here the output for `flutter doctor -v`  : 
```
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-x64, locale en-CH)
    • Flutter version 2.8.1 at /Users/mboussaid/Workspace/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (13 days ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/mboussaid/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] IntelliJ IDEA Ultimate Edition (version 2021.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5486

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (2 available)
    • iPhone 13 (mobile) • C882CB00-EB39-47F3-9EB0-4DF30BCC2B72 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 96.0.4664.110

! Doctor found issues in 2 categories.
```

A test that can reproduice that: 

This can be an example of test: 

```
  var _product = ScannedProduct(
      barcode: '123456789',
      name: 'Test Product',
      frontImageUrl:
          'https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png',
      ingredientsImageUrl:
          'https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png',
      ingredients: 'Oeuf, Lait',
      brands: 'Test Brands',
      countries: 'Test Countries',
      additives: 'E100, E500, E120, E330',
      labels: 'Test, Vegan, Kosher',
      categories: 'Test Categories',
      nutriScore: 'A',
      novaScore: '3',
      ecoScore: 'B',
      favorite: 'true',
      blacklist: 'false');

  testWidgets('Product Details UI tests', (WidgetTester tester) async {
    await tester.runAsync(() async {
      await tester.pumpWidget(MaterialApp(
          localizationsDelegates: AppLocalizations.localizationsDelegates,
          supportedLocales: AppLocalizations.supportedLocales,
          home: UpdateProduct(scannedProduct: _product)));

      await tester.pump(const Duration(seconds: 10));
      await tester.pumpAndSettle();

      expect(find.text('Name*'), findsOneWidget);
    });
  }, skip: false);
```

Where `ScannedProduct` is the product class model 
`UpdateProduct` is my screen for updating a product, in which I call `OpenFoodFactsAPI.getProduct` : 

And with the previous error I am getting this worning: 

```
Warning: At least one test in this suite creates an HttpClient. When
running a test suite that uses TestWidgetsFlutterBinding, all HTTP
requests will return status code 400, and no network request will
actually be made. Any test expecting a real network connection and
status code will fail.
```

**Comment by peterwvj** [comment]
I noticed that you are using Flutter 2.8.1. I was wondering whether the problem could be produced using Flutter 2.5.3 (the stable release that came before 2.8.0). Recently, I had to downgrade my app to built with 2.5.3 due to problems with the latest Flutter SDK. I've seen people advice against using 2.8.0 due to numerous other problems with that release. Fortunately, downgrading/upgrading Flutter so that might be worth a try.

Can the test be rewritten to not use widgets or is that I requirement? Can you make the test more self-contained so I can run it directly on my machine? Can I see the full .dart file?

**Comment by MohamedFBoussaid** [comment]
Thanks @peterwvj I just downgrade the version and the test passed ! It seems there is a regression on the flutter version. 
I will close the issue.

**Comment by peterwvj** [comment]
Glad to hear that you made it work 👍
