### ISSUE TITLE
Add a method to return a localized taxonomy translation url

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-dart#348]
### What
- [ ] Add a method to get localized taxonomy translation urls
  - Structure: https://world-fr.openfoodfacts.org/categories?translate=1
  - https://world-LC.openfoodfacts.org/TAXONOMY_NAME?translate=1
- [ ] Add a method to get localized Crowdin URL for Open Food Facts
  - https://crowdin.com/project/openfoodfacts/fr
### Why
- We have a section in the app on how to contribute to the project, but there's no way to help with taxonomy translation, which is important.

**Comment by monsieurtanuki** [comment]
Done in #372.
