### ISSUE TITLE
Add support for product/score readiness support

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-dart#350]
### What
- Add support for score readiness support
### Why
- to support that kind of features, without building an ad-hoc backend.
![image](https://user-images.githubusercontent.com/1689815/147817132-2f25fe5c-cb26-46d9-a079-f8862e73eebf.png)

### How
- A simplistic way for apps to monitor whether the product is ready would be to check for states at every app opening/daily/whatever. 
- They would call a new method with the product barcode (and potentially scores): is_product_ready(ecoscore), is_product_ready(ecoscore,nutriscore), is_product_ready(ecoscore,nutriscore, ingredients)
- When Nutri-Score, Eco-Score and ingredients are computed, the method would return a specific value `product_ready=true`
- The app would then decide how to surface it to the user

### Note
- This is a bit close to the Improvements that was added to the app a while ago, but it is assuming more passive users, and the absence of a self-service mobile contribution pipeline in the app.

**Comment by monsieurtanuki** [comment]
### Smoothie ###
That would mean doing that only for a implicitly restricted list of products, like the products I created on my smartphone, right? Or the products where I ticked the "alert me" checkbox (unticked by default). We can't do that on 1K+ products each time we're opening the app.

### off-dart ###
* The input would be a list of barcodes
* The output would be a `Map<barcode, ScoreReadiness>`, where `ScoreReadiness` would be a new simple class with three boolean fields like `bool ecoscoreReady; bool nutriscoreReady; bool ingredientsReady; `

**Comment by monsieurtanuki** [comment]
Done in #351: now it's time for smoothie to work on it!
