### ISSUE TITLE
Don't expose unnecessary user credentials

### ISSUE THREAD

**Issue by M123-dev** [openfoodfacts/openfoodfacts-dart#354]
Currently, the user credentials are always added to the header for every request, even for Get requests. This is an unnecessary security risk, we should only add this where necessary. 

In addition, things like `searchProducts` or `getRandomInsight` have a user as a required field. We probably don't need that in most cases

**Comment by monsieurtanuki** [comment]
@M123-dev I don't share your worries about sending the user even for GET requests (as long as it's httpS) - assuming that there's a point of doing it (statistics?).
But I would definitely be in favor of uniformity for at least the `User` parameter:
| positional `User` | positional `User?` | named `User?` | required `User` | no `User` at all |
| --- | --- | --- | --- | --- |
| `saveProduct` | `searchProducts` | `getProductRaw` | `setProductImageAngle` | `getProductUri` |
| `addProductImage` | `getProductList` | `getProduct` | `setProductImageCrop` | `getAutocompletedSuggestions` |
| `getRandomInsight` |  | `getProductFreshness` | `unselectProductImage` | `resetPassword` |
| `getProductInsights` | | `getTaxonomy` * |  `register` | `getEcoscoreHtmlDescription` |
| `extractIngredients` | | `getRobotoffQuestionsForProduct` | | `getKnowledgePanels` |
| `login` | | `postInsightAnnotation` | | `getOrderedNutrients` |
| deprecated `queryPnnsGroup` | | `getIngredientSpellingCorrection` | |
| `getRandomRobotoffQuestion` | | | |

To a lesser extent, there's something to do for `QueryType`s parameters.

**Comment by monsieurtanuki** [comment]
> I don't share your worries about sending the user even for GET requests (as long as it's httpS)

That means that we should get rid of apparently superfluous user parameters for GET requests that are _not_ in https.

**Comment by monsieurtanuki** [comment]
As long as it's httpS we don't really care. And if it's mere http the developer knows that it's dangerous, security-wise.
I think we can close.

**Comment by M123-dev** [comment]
The original advice came from pierre but I agree with you here that it is not a main prioritry task
