### ISSUE TITLE
Can't save product nutriment units with MILLI_G, MICRO_G and other types

### ISSUE THREAD

**Issue by nullbtb** [openfoodfacts/openfoodfacts-dart#357]
**Describe the bug**
When I pass a Product which contains nutrients, the client sends the actual dart Unit enum string value rather than a string representation of the unit.  This means that the outgoing request is sent to the back end with the string representation of the dart units, something like this: nutriment_calcium_unit=MILLI_G instead of nutriment_calcium_unit=mg.  This results in the product having an unknown unit type for that nutrient.  For the dart enum value of G, KCAL, KJ it works because that is the same as their scientific text representation g, kcal, kj.  However MILLI_G, MICRO_G, and all the other enums where the unit is different from the scientific textual representation fail.

**To Reproduce**
1. Create a product
2. Assign nutriments to it which contain MILLI_G or MICRO_G such as calcium, vitamin d, vitamin b12, etc.
3. Save product

**Expected behavior**
The product unit should be persisted with a valid mg and μg unit types so that I can retrieve it in the future.  Instead, the next time I retrieve this same product I see UNKNOWN for all MILLI_G or MICRO_G units.

**package information:**
Openfoodfacts package version:
1.8.1

**Comment by monsieurtanuki** [comment]
Hi @nullbtb!
I was able to reproduce your bug, and it will be fixed today.

**Comment by monsieurtanuki** [comment]
@nullbtb Fixed in the currently available version 1.9.1

**Comment by nullbtb** [comment]
Thank you @monsieurtanuki!
