### ISSUE TITLE
Add support for the multilingual text field `packaging_text_XX` 

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-dart#379]
### What

- [ ] Add support for the multilingual text field `packaging_text_XX` that enables users to input the recycling instructions
- This fields behaves exactly like the ingredients_text_XX, and the mechanism to fill it is exactly the same (get the OCR from the selected `packaging_XX` image, have the user check it, and then POST it to packaging_text_XX)
### Why
- Packaging is a crucial component in Eco-Score computations, and it should be easy to input those recycling instructions that are then parsed server side to compute packaging shapes and packaging materials
### Part of
- #191

**Comment by monsieurtanuki** [comment]
Done in #380.
