### ISSUE TITLE
How can I find the "allergens" ?

### ISSUE THREAD

**Issue by waeldimassi** [openfoodfacts/openfoodfacts-dart#39]
Thanks for the great work !! 
Quick question, how can I find the allergens from the response ?

**Comment by PrimaelQuemerais** [comment]
Hi,
Allergens are not supported by the plugin yet. I'll take a look at it in the afternoon 😉

**Comment by PrimaelQuemerais** [comment]
I've just updated the package to support Allergens (v0.3.7), you can now access allergences through Product.allergens.

Hope that helps
