### ISSUE TITLE
Autocomplete/search for taxonomies

### ISSUE THREAD

**Issue by monsieurtanuki** [openfoodfacts/openfoodfacts-dart#395]
**Is your feature request related to a problem? Please describe.**
In case the end-user wants to type in a taxonomy value (e.g. `brea`) we should be able to list all the names for this taxonomy that contain this text (e.g. 'Breads', 'Crips breads', ...)

**Describe the solution you'd like**
Inputs:
1. language
2. country
4. taxonomy
5. text
7. fields

Outputs:
* all the fields of all the taxonomy values that match the text

**Additional context**
This could be used as an autocomplete feature, or as a simple search feature.

**Comment by stephanegigandet** [comment]
This is the API we have today, that is used on the website for autocomplete suggestions:
https://world.openfoodfacts.org/cgi/suggest.pl?tagtype=categories&lc=fr&term=cam

**Comment by monsieurtanuki** [comment]
Thank you @stephanegigandet for your answer. Oops, actually it already existed as `getAutocompletedSuggestions`...
Not as I expected it (no fields, just "name"), but I guess that's good enough.
