### ISSUE TITLE
Allow to construct the URL for an arbitrary list of products

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-dart#403]
### What
- I'm designing screens for a simple list feature (based on Android v1), and one nice feature is getting a web url of your lists
- Allow to construct the URL for an arbitrary list of products
  - https://world.openfoodfacts.org/search?code=3254560079458,1234

**Comment by monsieurtanuki** [comment]
I think it's already there:
```dart
static Future<SearchResult> getProductList(
  User? user,
  ProductListQueryConfiguration configuration, {
  QueryType? queryType,
}) async {
  final Uri uri = UriHelper.getUri(
    path: 'products/${configuration.barcodes.join(',')}.json',
    queryParameters: configuration.getParametersMap(),
    queryType: queryType,
  );
...
```

**Comment by teolemon** [comment]
thanks @monsieurtanuki 
closing. meanwhile, here's a sneakpeak: 
<img width="569" alt="image" src="https://user-images.githubusercontent.com/1689815/156546909-680b1e24-0e89-414c-912f-4b316d078ed3.png">
