### ISSUE TITLE
Limit for number of products in "getProductList"?

### ISSUE THREAD

**Issue by monsieurtanuki** [openfoodfacts/openfoodfacts-dart#407]
**Describe the potential bug**
`OpenFoodAPIClient.getProductList` takes a list of barcodes as an input parameter, and concatenates them in a GET url that retrieves the product data.
But there may be limits in the url length.

**Preliminary checks**
From what I found on the internet the url max length is around 2000 characters.
Let's say that we need to provide enough barcodes to go to 3000 characters, and see what happens (does it crash? Do we get all the products that match the barcodes, or only the one that match the first 300 barcodes?)

**Actions**
A solution might be to change the request as POST, or to ask the same thing to the server side but with another syntax.

**Comment by monsieurtanuki** [comment]
That was a good idea:
```html
<html>
<head><title>414 Request-URI Too Large</title></head>
<body bgcolor="white">
<center><h1>414 Request-URI Too Large</h1></center>
<hr><center>nginx/1.10.3</center>
</body>
</html>
```

In my tests it looks like 8000 characters is the limit.

cf. #105: @teolemon @stephanegigandet Is there another way (like POST) to get a list of products than https://world.openfoodfacts.dev/products/8024884500403,3263855093192,3045320001570,3021762383344,4008400402222,3330720237255,3608580823513,3700278403936,3302747010029,3608580823490,3250391660995,3760020506605,8722700202387,3330720237330,3535800940005,20000691,3270190127512.json?fields=code,product_name?

**Comment by AshAman999** [comment]
I am new to this repo and eager to contribute, 
As it seems backend also needs to be ready to accept the changes if we are making a post request to get the data .

```
// thought of something like this instead of a get request
List<String> foodList = ['13434','343131','343131'];
  http.Response response = await http.post(
    Uri.parse('http://some_random_url'),
    headers: <String, String>{
      'Content-Type': 'application/json; charset=UTF-8',
    },
    body: jsonEncode(
      {
        'foodList': foodList,
      },
    ),
  );
```

if possible can i work on the front end part of this issue, a little bit of help in the context where to make the changes would help me a lot .
Thanks :)

**Comment by monsieurtanuki** [comment]
Hi @AshAman999! First we definitely need some changes on the server side, or another existing URL.
ping @stephanegigandet  @teolemon

**Comment by stephanegigandet** [comment]
@monsieurtanuki the OFF API accepts all parameters as POST parameters, but don't mix and match them: either send only query parameters, or only POST parameters.

For the Dart package, it's probably best to use POST for all requests. GET is mostly used for debugging purposes.

**Comment by stephanegigandet** [comment]
e.g. use this: https://world.openfoodfacts.dev/api/v2/search?code=8024884500403,3263855093192,3045320001570,3021762383344,4008400402222,3330720237255,3608580823513,3700278403936,3302747010029,3608580823490,3250391660995,3760020506605,8722700202387,3330720237330,3535800940005,20000691,3270190127512.json&fields=code,product_name

but send parameters with POST

**Comment by monsieurtanuki** [comment]
Thank you @stephanegigandet!
@AshAman999 I had already coded tests for this issue; I'm about to send a PR.
But I'll create another issue just for you, from @stephanegigandet's "it's probably best to use POST for all requests".
