### ISSUE TITLE
It's probably best to use POST for all requests

### ISSUE THREAD

**Issue by monsieurtanuki** [openfoodfacts/openfoodfacts-dart#414]
**Is your feature request related to a problem? Please describe.**
cf. @stephanegigandet's comment in #407.

**Describe the solution you'd like**
The impact would be all GET queries in `openfoodfacts.dart`, that should be changed into POST queries.

**Describe alternatives you've considered**
In most cases we don't _need_ it because there are only rare cases where we can reach the 8000 character limit for a URL.
But that would look less artisanal without all the parameters in the GET URL.

**Additional context**
All parameters must be in the same side; in our case, in the POST parameter side.
Could solve #354 too.
It would also be probably a good idea to add `Uri getUri({final QueryType? queryType});` to `AbstractQueryConfiguration`.
For test purposes, a new method in `HttpHelper` that creates a GET URL with the same parameters as method `doPostRequest` could be helpful.

**Comment by monsieurtanuki** [comment]
ping @AshAman999

**Comment by AshAman999** [comment]
@monsieurtanuki  I looked into the file where this code was and can probably come up with the solution, will raise a pr when done, though i am not sure about unit testing of the code as i have not done before, should i go ahead with my work?

**Comment by monsieurtanuki** [comment]
@AshAman999 I'm a bit worried when you say "come up with the solution": in my mind you just have to change each `doPostRequest` with a `doPostRequest`, and there should be no impact at all on unit tests.
I suggest that you just do one change, e.g. for method `getProductString`, create a PR and we'll see if it's the good direction.

**Comment by AshAman999** [comment]
Okay, 
I will raise a pr soon
