### ISSUE TITLE
Keeping track of Product Views through Anonymous Data

### ISSUE THREAD

**Issue by Raj2503** [openfoodfacts/openfoodfacts-dart#425]
We can add the functionality to keep **track of the views** a certain product is getting, thereby providing us with essential information about which products are **liked or generally bought** by people.

Using this data, we can improve the Open Food Facts AI and create a section for **Most Popular Products**.

**Comment by monsieurtanuki** [comment]
As pointed out [here](https://github.com/openfoodfacts/openfoodfacts-dart/pull/386#issuecomment-1073763346), that should probably rather be done on the server side than on the client side.
In addition to that, I believe that the natural order of the results is the product popularity, but maybe I'm wrong.
Maybe a good reason to use Folksonomy, which is already implemented.

**Comment by Raj2503** [comment]
@monsieurtanuki thank you for the amazing insight.
It opened me up to a broader perspective of the problem.

Please correct me if I am wrong again, but I would suggest implementing [Google Analytics  APIs](https://developers.google.com/analytics#:~:text=APIs%20for%20reporting%20and%20configuration) on the server-side for this purpose.
**Google Analytics** can really simplify the problem according to me.

It can prevent falsifying of data as pointed out [here](https://github.com/openfoodfacts/openfoodfacts-dart/pull/386#issuecomment-1073763346), as it **doesn't record multiple Event API** calls from the same user for a default **Time Frame**. 

Also, it can **track per product views** using the [Real-Time Reporting API](https://developers.google.com/analytics/devguides/reporting/realtime/v3), making it a lot easier to get started with Most Popular Section.

**Comment by M123-dev** [comment]
When I remember correctly there is already some kind of loose tracking of some metrics, but Open Food Facts has a big focus on privacy therefore I guess Google Analytics isn't in use.

 But as monsieurtanuki already pointed out, this repository has nothing to do with tracking metrics but is just a wrapper around the OpenFoodFacts API. You'll probably get a better answer if you either ask in the [server repository](https://github.com/openfoodfacts/openfoodfacts-server) or even better on [Slack ](https://slack.openfoodfacts.org/)

**Comment by monsieurtanuki** [comment]
Hi @Raj2503! As @M123-dev's just pointed out, that concerns rather the server side. I keep my energy for the flutter/dart side :)

**Comment by teolemon** [comment]
I'm closing, as we indeed already compute a popularity index server side, and have also a https://github.com/openfoodfacts/openfoodfacts-monitoring repository
