### ISSUE TITLE
README.md: List of apps using the SDK

### ISSUE THREAD

**Issue by g123k** [openfoodfacts/openfoodfacts-dart#432]
Hi everyone,

After a discussion on Slack (https://openfoodfacts.slack.com/archives/CJJS77W6B/p1649139667792409), some people were asking for examples of apps using the Dart SDK.

Wouldn't it be nice to have a section in the README to link to some of them? (eg: Smoothie)

**Comment by teolemon** [comment]
Sounds like a good idea

**Comment by g123k** [comment]
Ok I will a add the section.
Except Smoothie, do you know other apps using the SDK?

**Comment by MohamedFBoussaid** [comment]
@g123k you are looking for the list of the (OFF) internal apps that are using the SDK or any app is using it?

**Comment by VaiTon** [comment]
I think even third party apps are welcome here as we want to showcase the use-cases of the dart library!

**Comment by MohamedFBoussaid** [comment]
@VaiTon  @g123k 
Here 2 apps : 

Gluten Scan: 
https://play.google.com/store/apps/details?id=com.healthyfood.gluten_free_app
https://apps.apple.com/ch/app/gluten-scanner/id1540660083?l=fr

Halal & Healthy: 
https://play.google.com/store/apps/details?id=com.TagIn.Tech.handh
https://apps.apple.com/ch/app/halal-healthy/id1603051382?l=fr

**Comment by peterwvj** [comment]
Fitness Tracker uses the SDK: https://play.google.com/store/apps/details?id=dk.cepk.fitness_tracker
