### ISSUE TITLE
Validity of a barcode

### ISSUE THREAD

**Issue by g123k** [openfoodfacts/openfoodfacts-dart#439]
On the Android app, [a barcode is valid if](https://github.com/openfoodfacts/openfoodfacts-androidapp/blob/develop/app/src/main/java/openfoodfacts/github/scrachx/openfood/utils/Utils.kt#L244):
- Its length is > 3
- Is an EAN 13
- Doesn't start with 977, 978 or 979

If I'm not wrong, we don't have these checks on Smoothie.
Should we implement them?

**Comment by g123k** [comment]
(It's better to talk about this in the Dart SDK)

Thanks for your two links @monsieurtanuki.
Maybe we should improve the `InvalidBarcodes` class by stating that only EAN13 and EAN8 are valid?

**Comment by monsieurtanuki** [comment]
The first steps would be to implement methods `isValidEAN8` and `isValidEAN13`. Then we'll see.

**Comment by g123k** [comment]
@monsieurtanuki This should be implemented in #444.
Please don't hesitate to add any comment on the PR 👍
