### ISSUE TITLE
Page(page: 10) not importing in openfoodfacts: ^1.14.0

### ISSUE THREAD

**Issue by Vishnu-Jmatics** [openfoodfacts/openfoodfacts-dart#447]
**Describe the bug**
`Page(page: 10)` not importing in openfoodfacts: ^1.14.0

**To Reproduce**
I'm developing a flutter application and it need the support of open-foods api for getting items by keyword.  For that I have set parameters like
 `PageSize(size: 1)`, 
`SearchTerms(terms: [searchText])`,
`SortBy(option: SortOption.PRODUCT_NAME)`,
**`Page(page: 10)`** 
etc. 

But **`Page(page: 10)`** shows syntax error always after I import 
import:

 `'package:openfoodfactsopenfoodfacts.dart';`

I don't know why this. I need to do this for pagination. Kindly let me know why this error so that I can forward with this feature. Thanks. 
      

**Screenshots**
![Screenshot 2022-04-19 120346](https://user-images.githubusercontent.com/45096096/163940610-d59131e0-d08c-4835-a2d6-cc6346dd1e16.png)

**package information:**
Openfoodfacts package version: `openfoodfacts: ^1.14.0`

**Comment by g123k** [comment]
Hi @Vishnu-Jmatics,

Thanks for your report.
I have tested on a new project and I don't have any issues with this class.

Are you certain that in your file, you don't import another file with also exports a `Page`?

**Comment by Vishnu-Jmatics** [comment]
@g123k  Thanks for the info. I 've checked it and shows this.

The name 'Page' is defined in the libraries 'package:flutter/src/widgets/navigator.dart' and 'package:openfoodfacts/model/parameter/Page.dart (via package:openfoodfacts/openfoodfacts.dart)'._ 

How can rectify this. Please help..

**Comment by g123k** [comment]
In your imports just say:

```
import 'package:flutter/src/widgets/navigator.dart' hide Page;
```

**Comment by M123-dev** [comment]
Otherwise if you at some point need both `Page` classes in a single file you can replace `hide Page;` with for example `as off;` then all imports from openfoodfacts would start with off.

`off.SearchTerms
off.Page
...
`

**Comment by Vishnu-Jmatics** [comment]
@g123k Yey great. _import 'package:flutter/material.dart'_ is not directly imported in file but I supposed it resides in _'package:flutter/material.dart'_. I 've replaced it it by **_import  'package:flutter/material.dart' hide Page;_**. Thanks for ur valuable response, I can forward with this.

**Comment by monsieurtanuki** [comment]
@g123k @M123-dev Well done guys! Perhaps one day we should refactor `Page` as `PageNumber`: that would be more explicit and less prone to ambiguity, import-wise.
