### ISSUE TITLE
api_getProduct_test.dart: OpenFoodAPIClient get products get knowledge panels (failed)   type 'Null' is not a subtype of type 'String' in type cast

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-dart#477]
❌ test/api_getProduct_test.dart: OpenFoodAPIClient get products get knowledge panels (failed)
  type 'Null' is not a subtype of type 'String' in type cast
  package:openfoodfacts/model/KnowledgePanelElement.g.dart 202:28  _$KnowledgePanelTableElementFromJson
  package:openfoodfacts/model/KnowledgePanelElement.dart 294:7     new KnowledgePanelTableElement.fromJson
  package:openfoodfacts/model/KnowledgePanelElement.g.dart 246:40  _$KnowledgePanelElementFromJson
  package:openfoodfacts/model/KnowledgePanelElement.dart 368:7     new KnowledgePanelElement.fromJson
  package:openfoodfacts/model/KnowledgePanel.g.dart 20:44          _$KnowledgePanelFromJson.<fn>
  dart:_internal                                                   ListIterable.toList
  package:openfoodfacts/model/KnowledgePanel.g.dart 21:12          _$KnowledgePanelFromJson
  package:openfoodfacts/model/KnowledgePanel.dart 119:7            new KnowledgePanel.fromJson
  package:openfoodfacts/model/KnowledgePanels.dart 13:37           new KnowledgePanels.fromJson
  package:openfoodfacts/model/KnowledgePanels.dart 27:25           KnowledgePanels.fromJsonHelper
  package:openfoodfacts/model/Product.g.dart 117:27                _$ProductFromJson
  package:openfoodfacts/model/Product.dart 424:28                  new Product.fromJson
  package:openfoodfacts/model/ProductResult.g.dart 16:21           _$ProductResultFromJson
  package:openfoodfacts/model/ProductResult.dart 20:7              new ProductResult.fromJson
  package:openfoodfacts/openfoodfacts.dart 205:48                  OpenFoodAPIClient.getProduct
  ===== asynchronous gap ===========================
  test/api_getProduct_test.dart [148](https://github.com/openfoodfacts/openfoodfacts-dart/runs/6731992484?check_suite_focus=true#step:7:278)7:43                            main.<fn>.<fn>

**Comment by teolemon** [comment]
First spotted during: https://github.com/openfoodfacts/openfoodfacts-dart/pull/475

**Comment by stephanegigandet** [comment]
probably the title of the nutrition table panel that was removed

**Comment by stephanegigandet** [comment]
@monsieurtanuki I deployed an hotfix on prod, to add back the title. On test the fix has not been merged and deployed yet.

I think it would be good if we can make the openfoodfacts-dart package consider all response fields as optional, apps should not crash if a field is missing, or renamed.

**Comment by monsieurtanuki** [comment]
@stephanegigandet I'm about to PR the "optional `title`" fix.

I don't know what to think about your suggestion of making all response fields optional: in a first approach I must say I'm not tempted and in a second approach I would say it's already late, so let's fix the issue first!
