### ISSUE TITLE
The following fields do not exist in off-dart products AFAIK

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-dart#481]
@teolemon I can work on "Packaging", but the following fields do not exist in off-dart products AFAIK:

- [ ] Origins of ingredients
- [x] Manufacturing places
- [x] EMB Codes
- [ ] Countries

_Originally posted by @monsieurtanuki in https://github.com/openfoodfacts/smooth-app/issues/2169#issuecomment-1149481786_

**Comment by M123-dev** [comment]
Can this be closed @monsieurtanuki

**Comment by monsieurtanuki** [comment]
* "origins" added in #509.
* "countries" were already in off-dart but were added later to Smoothie (in the default list of fields).
