### ISSUE TITLE
Sharing a product via social media should not add parameters

### ISSUE THREAD

**Issue by M123-dev** [openfoodfacts/openfoodfacts-dart#507]
### What
- When sharing a product:

Schauen Sie sich dieses Produkt auf Open Food Facts an: https://de-de.openfoodfacts.org/product/8027547000012?app_name=Smoothie+-+OpenFoodFacts&app_version=3.4.5%2B669&app_uuid=40cfc360ac0d4596&app_platform=android%2BSP1A.210812.016.G991BXXS5CVFB&comment=+-+Smoothie+-+OpenFoodFacts+-+3.4.5%2B669+-+android%2BSP1A.210812.016.G991BXXS5CVFB

- We should not add the app name version uuid platform and all the other stuff

**Comment by teolemon** [comment]
😱 @M123-dev @monsieurtanuki bumping to P0

**Comment by M123-dev** [comment]
Fixed already

> Schauen Sie sich dieses Produkt auf Open Food Facts an: https://de.openfoodfacts.org/product/4015016000100

**Comment by M123-dev** [comment]
Wait no, we need more checking, I think we just fixed this in smoothie locally and not in here
