### ISSUE TITLE
API v2: allergens_tags:=-en:gluten

### ISSUE THREAD

**Issue by monsieurtanuki** [openfoodfacts/openfoodfacts-dart#526]
https://us.openfoodfacts.org/api/v2/search?categories_tags_en=snacks&allergens_tags:=-en:gluten&page_size=5

**Comment by monsieurtanuki** [comment]
Not 100% sure how I should deal with this one.

Of course, there are 14 "main" allergen tags, the ones in the preferences:
* `en:gluten`
* `en:milk`
* `en:soybeans`
* `en:eggs`
* `en:nuts`
* `en:fish`
* `en:mustard`
* `en:sesame-seeds`
* `en:crustaceans`
* `en:sulphur-dioxide-and-sulphites`
* `en:celery`
* `en:molluscs`
* `en:lupin`
* `en:peanuts`

But there are also "less English" and less normalized values in `Product.allergens.ids`, like those:
* `fr:avoine`
* `fr:gs1-t4078-ml`
* `fr:e224`
* `fr:ble-d-epeautre`
* `fr:e224-sulfites`
* `es:metabisulfito`
* `en:trigo`
* `en:ble`
* `de:fruits-à-coque`
* `fr:tournesol`
* `en:sellerie`
* `pl:ser`
* `pl:pirosiarczyn`
* `hr:pšenica`
* `fr:metabisulphite-de-sodium`
* `es:semillas-de-soja`
* `en:oeuf`
* `de:schafkäse`
* `bg:сметана`

I assume that just filtering on the main 14 allergen tag values makes sense, and we need the developers not to worry if it's `sesame-seeds`, `en:sesame-seeds` or `en:sesame_seeds`.

**Comment by teolemon** [comment]
Other values should be taxonomized server side, so we focus on the 14 values as listed here: https://static.openfoodfacts.org/data/taxonomies/allergens.json
