### ISSUE TITLE
License appears unknown 

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-dart#548]
Apache License appears unknown 

<img width="320" alt="image" src="https://user-images.githubusercontent.com/1689815/188096597-c1d1b832-fc11-4cbb-a916-c7a427028fc6.png">

**Comment by yashsharma81** [comment]
@teolemon i am working on this issue

**Comment by yashsharma81** [comment]
@teolemon can you please provide the path for above ScreenShot if possible

**Comment by M123-dev** [comment]
@yashsharma81, its here on the right side: https://pub.dev/packages/openfoodfacts

**Comment by yashsharma81** [comment]
@M123-dev can you please tell that how to contribute in dart packages?

**Comment by monsieurtanuki** [comment]
Still not OK with 1.30.0 :(
