### ISSUE TITLE
Add support for last edit/image/entry dates

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-dart#557]
### Description
Add support for last edit/image/entry dates
"entry_dates_tags":["2012-06-25","2012-06","2012"]
"last_check_dates_tags":["2018-11-08","2018-11","2018"],
"last_checked_t":1541687984,
"last_checker":"beniben",
"last_edit_dates_tags":["2022-08-21","2022-08","2022"],
"last_editor":"roboto-app",
"last_image_dates_tags":["2021-12-30","2021-12","2021"],
"last_image_t":1640852418,
"last_modified_by":"roboto-app",
"last_modified_t":1661057626,

**Comment by anshpathania7** [comment]
In this all fields are Nullable except `entry_date_tags` right?

**Comment by M123-dev** [comment]
@anshpathania7 all of these fields are nullable as you can specifically request only certain fields

**Comment by anshpathania7** [comment]
@M123-dev Okay got it, also for the List of Dates, It's coming List of String from api, should it be converted into DateTime object?

**Comment by M123-dev** [comment]
I think we can leave it in strings for now, as it's just a date but no time. Maybe @monsieurtanuki has another idea for that

**Comment by monsieurtanuki** [comment]
For consistency, I would consider timestamps as `DateTime?`:
```dart
  @JsonKey(
      name: 'last_modified_t',
      includeIfNull: false,
      fromJson: JsonHelper.timestampToDate,
      toJson: JsonHelper.dateToTimestamp)
  DateTime? lastModified;
```

I would consider the rest as `String?` and `List<String>?`.
