### ISSUE TITLE
Robotoff test failing

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-dart#559]
### Description
Robotoff test failing. Note we did a recent deployment
❌ test/api_getRobotoff_test.dart: OpenFoodAPIClient get robotoff insights get product insights PROD (failed)
  Expected: 'found'
    Actual: 'no_insights'
     Which: is different.
            Expected: found
              Actual: no_insight ...
                      ^
             Differ at offset 0
  
  package:test_api                      expect
  test/api_getRobotoff_test.dart 103:7  main.<fn>.<fn>

**Comment by teolemon** [comment]
❌ test/api_searchProducts_test.dart: OpenFoodAPIClient search products search with all sort-by options (failed)
  Expected: not [
              '3242272346050',
              '400[17](https://github.com/openfoodfacts/openfoodfacts-dart/actions/runs/3082401942/jobs/4982068051#step:7:25)24819905',
              '3270160717668',
              '4001724819806',
              '7613035648494',
              '7613035648463',
              '3242272347552',
              '10086988',
              '3038352876506',
              '40017248[18](https://github.com/openfoodfacts/openfoodfacts-dart/actions/runs/3082401942/jobs/4982068051#step:7:26)908',
              '4001724819400',
              '20001650',
              '3242272345053',
              '3270160890170',
              '3270160717323',
              '3270160371983',
              '3242272345558',
              '4001724819509',
              '3068111708229',
              '3270160890842',
              '20291013',
              '20711948',
              '3270160891139',
              '3242272347057',
              ...
            ]
    Actual: [
              '3242272346050',
              '40017248[19](https://github.com/openfoodfacts/openfoodfacts-dart/actions/runs/3082401942/jobs/4982068051#step:7:27)905',
              '3270160717668',
              '4001724819806',
              '7613035648494',
              '7613035648463',
              '3242272347552',
              '10086988',
              '3038352876506',
              '4001724818908',
              '4001724819400',
              '[20](https://github.com/openfoodfacts/openfoodfacts-dart/actions/runs/3082401942/jobs/4982068051#step:7:28)001650',
              '324[22](https://github.com/openfoodfacts/openfoodfacts-dart/actions/runs/3082401942/jobs/4982068051#step:7:30)7[23](https://github.com/openfoodfacts/openfoodfacts-dart/actions/runs/3082401942/jobs/4982068051#step:7:31)45053',
              '3270160890170',
              '3270160717323',
              '3270160371983',
              '3[24](https://github.com/openfoodfacts/openfoodfacts-dart/actions/runs/3082401942/jobs/4982068051#step:7:32)2[27](https://github.com/openfoodfacts/openfoodfacts-dart/actions/runs/3082401942/jobs/4982068051#step:7:35)2345558',
              '4001724819509',
              '30681117082[29](https://github.com/openfoodfacts/openfoodfacts-dart/actions/runs/3082401942/jobs/4982068051#step:7:37)',
              '[32](https://github.com/openfoodfacts/openfoodfacts-dart/actions/runs/3082401942/jobs/4982068051#step:7:40)70160890842',
              '20291013',
              '20711948',
              '3270160891139',
              '3242272[34](https://github.com/openfoodfacts/openfoodfacts-dart/actions/runs/3082401942/jobs/4982068051#step:7:42)7057',
              ...
            ]
  Should be different for SortOption.NOTHING and SortOption.POPULARITY

**Comment by monsieurtanuki** [comment]
@teolemon I do think it's a problem on the server side. Have they changed their criteria regarding sort options, or the default sort option?

**Comment by monsieurtanuki** [comment]
Looks like it's solved now.
