### ISSUE TITLE
Don't add user credentials systematically for POST requests

### ISSUE THREAD

**Issue by monsieurtanuki** [openfoodfacts/openfoodfacts-dart#560]
> @M123-dev @monsieurtanuki Why are we sending credentials on a read query in the first place ?

I guess that's a combination of adding user credentials on POST for good reasons (#420), and switching most queries from GET to POST for good reasons (#414).
![Capture d’écran 2022-09-18 à 18 16 09](https://user-images.githubusercontent.com/11576431/190917184-f8659c03-6e5e-403a-b36c-b50ef3d3e1f9.png)

The solution would be to add an optional parameter to the `doPostRequest` method, stating if we want to add user credentials (defaults to `false`, would be `true` at least for photos) (today implicitly it's `true`, which causes the bug).
@teolemon Ok with that fix?

_Originally posted by @monsieurtanuki in https://github.com/openfoodfacts/openfoodfacts-dart/issues/519#issuecomment-1250341248_

**Comment by teolemon** [comment]
- Related: https://github.com/openfoodfacts/openfoodfacts-dart/issues/553

**Comment by monsieurtanuki** [comment]
Currently tap dancing with tests, but when I'm done I'll PR something like this:

Credentials for the following methods (and user name in the header):
*saveProduct
* postInsightAnnotation
* login
* _callProductImageCrop
* unselectProductImage

No credentials for the following methods (still, user name in the header):
* product search in general
* getIngredientSpellingCorrection
* extractIngredients
* extractPackaging
* getAutocompletedSuggestions
* getOrderedNutrientsJsonString

**Comment by teolemon** [comment]
postInsightAnnotation >> We should not post credentials for this one, I don't quite remember the exact way to log in (cc @raphael0202 ) but we definitely do not require password (and it might provoke failures such as https://github.com/openfoodfacts/smooth-app/issues/2954)

**Comment by monsieurtanuki** [comment]
ok

**Comment by monsieurtanuki** [comment]
The original issue was fixed by #561.
Feel free to create a new issue if needed, especially around the cookie/authentication for Robotoff.
