### ISSUE TITLE
Upgrade to dart 2.17 (enum with fields and methods)

### ISSUE THREAD

**Issue by monsieurtanuki** [openfoodfacts/openfoodfacts-dart#571]
### Why - Problem description
With 2.17, we could use `enum`s with fields and methods.

### What - Proposed solution
Upgrade to dart 2.17.

### Additional context
Not sure what the impact would be.

**Comment by M123-dev** [comment]
Sounds good @monsieurtanuki I think the only impact is that everyone who uses this package has to upgrade too. So a breaking change. Maybe we should be more open with breaking changes and not put all of them on a never ending queue

**Comment by monsieurtanuki** [comment]
Thank you @M123-dev for your answer!
I would call it a "minor" breaking change, as [dart 2.17 is already 6 month old](https://dart.dev/guides/whats-new#may-11-2022-217-release) and there's only a minor impact on the `pubspec.yaml`. (yes it's 2.17 we need, not 2.15)
Let's go then: I start with #566, then we can see how things work (potential rejections by developers using off-dart?), then we can roll out the rest of the `enum`s.

**Comment by monsieurtanuki** [comment]
We now use dart 2.17 from #570.
