### ISSUE TITLE
❌ test/api_getRobotoff_test.dart: OpenFoodAPIClient get robotoff insights get random insight (failed)

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-dart#575]
### Description
❌ test/api_getRobotoff_test.dart: OpenFoodAPIClient get robotoff insights get random insight (failed)
  Expected: not null
    Actual: <null>
  
  package:test_api                      expect
  test/api_getRobotoff_test.dart 111:7  main.<fn>.<fn>

**Comment by monsieurtanuki** [comment]
Fixed in #570.
