### ISSUE TITLE
pub.dev -10pts because we don't have a license

### ISSUE THREAD

**Issue by monsieurtanuki** [openfoodfacts/openfoodfacts-dart#578]
### Why - Problem description
As stated today in [pub.dev](https://pub.dev/packages/openfoodfacts/score):
> 0/10 points: Use an OSI-approved license
No license was recognized.
Consider using an [OSI-approved license](https://opensource.org/licenses) in the LICENSE file to make it more accessible to the community.

![Capture d’écran 2022-10-11 à 19 22 35](https://user-images.githubusercontent.com/11576431/195158392-aa1c355f-f789-4fd1-b9a9-e1c5fc8a4017.png)

**Comment by teolemon** [comment]
- #548
