### ISSUE TITLE
All ProductImages returned have null URL

### ISSUE THREAD

**Issue by mariusgabriel1** [openfoodfacts/openfoodfacts-dart#581]
### Description
When searching a product the images returned have url null

### Expected behavior
 On the website the product has image so it also should be returned in the call

### Package information
[^1.25.0](openfoodfacts: ^1.25.0)

### Additional context
```
ProductSearchQueryConfiguration configuration = ProductSearchQueryConfiguration(parametersList: [
      SearchTerms(terms: [query])
    ],fields: [ProductField.ALL]);

    OpenFoodAPIConfiguration.userAgent = UserAgent(name: 'appname', version: '1', system:'iOS', url:'', comment:'');

    var result = await OpenFoodAPIClient.searchProducts(null, configuration);
    var products = result.products ?? [];

for (var product in products) {
      var title = product.productName ?? "";
      var brand = product.brands ?? "";
      var barcode = product.barcode ?? "";
      var quantity = product.quantity ?? "";
      var image = product.images?.firstWhereOrNull((element) => element.url != null)?.url ?? "";
//both product.images and selectedImages have property url null
//....
}
```

**Comment by monsieurtanuki** [comment]
Hi @mariusgabriel1!
Actually we rather use `ImageHelper.buildUrl(String barcode, ProductImage image)`.
Tell me if it works, and then we'll think about how to make it more developer-friendly.

**Comment by mariusgabriel1** [comment]
> Hi @mariusgabriel1! Actually we rather use `ImageHelper.buildUrl(String barcode, ProductImage image)`. Tell me if it works, and then we'll think about how to make it more developer-friendly.

ok that works, thank you!
