### ISSUE TITLE
Folksonomy tests were 500

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-dart#587]
### Description
❌ test/api_folksonomy_test.dart: OpenFoodAPIClient Folksonomy getProductStats - all (failed)
❌ test/api_folksonomy_test.dart: OpenFoodAPIClient Folksonomy getProductStats - found (failed)
❌ test/api_folksonomy_test.dart: OpenFoodAPIClient Folksonomy getProductStats - not found (failed)
❌ test/api_folksonomy_test.dart: OpenFoodAPIClient Folksonomy getProducts - found key (failed)
❌ test/api_folksonomy_test.dart: OpenFoodAPIClient Folksonomy getProducts - found key and value (failed)
❌ test/api_folksonomy_test.dart: OpenFoodAPIClient Folksonomy getProducts - not found key (failed)
❌ test/api_folksonomy_test.dart: OpenFoodAPIClient Folksonomy getProducts - not found key and value (failed)
❌ test/api_folksonomy_test.dart: OpenFoodAPIClient Folksonomy getProductTags - found (failed)
❌ test/api_folksonomy_test.dart: OpenFoodAPIClient Folksonomy getProductTags - not found (failed)
❌ test/api_folksonomy_test.dart: OpenFoodAPIClient Folksonomy getProductTag - found (failed)
❌ test/api_folksonomy_test.dart: OpenFoodAPIClient Folksonomy getProductTag - not found (failed)
❌ test/api_folksonomy_test.dart: OpenFoodAPIClient Folksonomy getProductTagWithSubKeys - found (failed)
❌ test/api_folksonomy_test.dart: OpenFoodAPIClient Folksonomy getProductTagWithSubKeys - not found (failed)
❌ test/api_folksonomy_test.dart: OpenFoodAPIClient Folksonomy getProductTagVersions - found (failed)
❌ test/api_folksonomy_test.dart: OpenFoodAPIClient Folksonomy getProductTagVersions - not found (failed)
❌ test/api_folksonomy_test.dart: OpenFoodAPIClient Folksonomy getKeys (failed)
❌ test/api_folksonomy_test.dart: OpenFoodAPIClient Folksonomy ping (failed)

**Comment by M123-dev** [comment]
Looks rather like the server is down, if even the ping fails

**Comment by monsieurtanuki** [comment]
@M123-dev Fair enough, but the `hello` passes
```dart
  /// "hello world"
  static Future<void> hello({
    final QueryType? queryType,
  }) async {
    final Response response = await HttpHelper().doGetRequest(
      UriHelper.getFolksonomyUri(
        path: '/',
        queryType: queryType,
      ),
      queryType: queryType,
    );
    _checkResponse(response);
  }
```

**Comment by teolemon** [comment]
The server was rebooted by @charlesnepote and it now works.
Unsure of the ground cause though
