### ISSUE TITLE
Request for feedback: new product WRITE API with structured JSON body and new packagings structure

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-dart#589]
We are designing a new API for packagings that we will be using in particular in the OFF Flutter app.

The corresponding issue on the server repo is https://github.com/openfoodfacts/openfoodfacts-server/issues/7564

We are designing a new API so that clients can specify the different packaging components of a product. The packagings will be in a complex structure, so we are departing from the existing API that uses flat form fields to a new API that will accept directly a JSON structure as input. While we are focusing first on packagings, this new API can gradually be extended to support other product fields.

It would be great to get your feedback and suggestions on this new API, for packagings in particular, but also for updating products in general.

**Comment by teolemon** [comment]
https://github.com/openfoodfacts/openfoodfacts-server/pull/7614

**Comment by stephanegigandet** [comment]
Implementation of the new API is almost done, so closing this in favor of #617
