### ISSUE TITLE
Add support for the Origins taxonomy

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-dart#596]
### What
- [ ] Add support for the Origins taxonomy
  - [x] We need support for autocomplete for the origin field: https://world.openfoodfacts.org/cgi/suggest.pl?tagtype=origins&term=fr&lc=en
  - [ ] We need support for the Partial taxonomy API

### Why
- https://github.com/openfoodfacts/smooth-app/issues/3149

**Comment by monsieurtanuki** [comment]
Autocomplete for ORIGINS is being implemented in #597.
@teolemon Not sure what "Partial taxonomy API" means.

**Comment by teolemon** [comment]
https://world.openfoodfacts.org/api/v2/taxonomy?tagtype=origins&include_root_entries=1&include_children=0&lc=fr&cc=fr
