### ISSUE TITLE
Add support to retrieve product attributes, remove harcoded attribute groups names

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-dart#60]
See https://wiki.openfoodfacts.org/Product_Attributes  for a description of product attributes.

It looks like @PrimaelQuemerais added some support for product attributes already:
https://github.com/openfoodfacts/openfoodfacts-dart/blob/master/lib/model/AttributeGroups.dart

But we should remove the harcoded names for attribute groups (nutritional_quality, processing, labels etc.): the server will add new attribute groups and attributes, and clients / libraries should not need to be updated.

**Comment by monsieurtanuki** [comment]
@stephanegigandet Can you assign this issue to me? Anyway I need it for smoothie, and I've somehow already fixed the code.

**Comment by PrimaelQuemerais** [comment]
Resolved in #65
Thank you @monsieurtanuki
