### ISSUE TITLE
Add product fields: contribution info

### ISSUE THREAD

**Issue by monsieurtanuki** [openfoodfacts/openfoodfacts-dart#618]
### Why - Problem description
cf. Smoothie's https://github.com/openfoodfacts/smooth-app/issues/3210:
> In the old app we had a tab to show contributions info (latest contributor, users that edited the page, etc.)

### What - Proposed solution
Check if we provide all the contribution fields, and implement those we don't:
cf. https://world.openfoodfacts.org/api/v2/product/3033710065066.json?fields=editors,editors_tags,photographers,photographers_tags,last_check_dates_tags,last_checked_t,last_checker,last_edit_dates_tags,last_editor,last_image_dates_tags,last_image_t,last_modified_by,last_modified_t

That means the following fields:
- [ ] editors
- [ ] editors_tags
- [ ] photographers
- [ ] photographers_tags
- [ ] last_check_dates_tags
- [ ] last_checked_t
- [ ] last_checker
- [ ] last_edit_dates_tags
- [ ] last_editor
- [ ] last_image_dates_tags
- [ ] last_image_t
- [ ] last_modified_by
- [ ] last_modified_t

**Comment by teolemon** [comment]
Note, many of those fields are partially or fully redondant, and many are not really useful.
We also have the opportunity to do this as a knowledge panel instead

**Comment by monsieurtanuki** [comment]
@teolemon If you assess that a new knowledge panel developed on the server side would meet your needs, feel free to close this issue.

**Comment by monsieurtanuki** [comment]
I don't know how deep we are supposed to go.

If we want to be at the same level as the website in READ mode...
![Capture d’écran 2022-11-22 à 13 34 37](https://user-images.githubusercontent.com/11576431/203315237-8bd7e9f5-5cc4-4988-9d1e-1993bd752d82.png)
...those are the product fields we need:
* `creator`: String
* `created_t`: timestamp
* `last_modified_by`: String
* `last_modified_t`: timestamp (we've already got it)
* `last_checker`: String
* `last_checked_t`: timestamp
* `editors_tags`: List<String>

No problem.

Less easy would be the history, available in WRITE mode - I don't know how to get that level of data, and if it's needed.
![Capture d’écran 2022-11-22 à 13 37 41](https://user-images.githubusercontent.com/11576431/203315864-bf752e41-432c-4465-9abe-9fcd8f97e5ce.png)
