### ISSUE TITLE
Invalid authentication sent to Robotoff during question answering

### ISSUE THREAD

**Issue by raphael0202** [openfoodfacts/openfoodfacts-dart#625]
See https://sentry.io/organizations/openfoodfacts/issues/3749073432/events/2638e00077e54c64abf983aaedb71838/?project=1415205&referrer=previous-event

'null' is sometimes sent as username in during `/insights/annotate` call.

**Comment by monsieurtanuki** [comment]
@raphael0202 Actually there are expected cases when the user is null, branded as "anonymousAnnotation" (in `question_page.dart`):
```dart
    if (OpenFoodAPIConfiguration.globalUser == null && insightId != null) {
      _anonymousAnnotationList.putIfAbsent(insightId, () => insightAnnotation);
    }
    await LoadingDialog.run<Status>(
      context: context,
      title: appLocalizations.saving_answer,
      future: OpenFoodAPIClient.postInsightAnnotation(
        insightId,
        insightAnnotation,
        deviceId: OpenFoodAPIConfiguration.uuid,
        user: OpenFoodAPIConfiguration.globalUser,
      ),
    );
```

There has been some refactoring here, so it's not easy to follow the history: which user should we use for those anonymous annotations?
