### ISSUE TITLE
Add support for the Knowledge Panels for Facets API

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-dart#629]
### What
- A new API that emulates knowledge panels but for facets  (eg /category/wines) has been created, and deployed to pre-prod
- Theoretically, the API should work exactly like the knowledge panels displayed on a product (same format)
- Only the endpoint changes. But that's theory at this point.
- https://facets-kp.openfoodfacts.net/docs#/knowledge-panel/knowledge_panel_knowledge_panel_get
- This unlocks value when implemented within https://github.com/openfoodfacts/smooth-app/issues/2737

### Part of
- #218

**Comment by sumit-158** [comment]
Eg:- for category-fr: fitou
https://facets-kp.openfoodfacts.net/knowledge_panel?facet_tag=category&value_tag=fr%3Afitou
