### ISSUE TITLE
Become a verified publisher

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-dart#631]
### Description

- Become a verified publisher
- https://dart.dev/tools/pub/verified-publishers
- https://pub.dev/create-publisher

**Comment by M123-dev** [comment]
Let me tell you something great. We are already 😄 
![grafik](https://user-images.githubusercontent.com/39344769/204874663-aee4c172-4428-484a-aa58-501296d8e7b3.png)
