### ISSUE TITLE
 OpenFoodAPIClient.getProductV3 status is int not String?

### ISSUE THREAD

**Issue by M123-dev** [openfoodfacts/openfoodfacts-dart#658]
### Description

```dart
  ProductQueryConfiguration config = ProductQueryConfiguration('3274080005003');
  ProductResultV3 product = await OpenFoodAPIClient.getProductV3(config);

```

Causes a type exception, because `type 'int' is not a subtype of type 'String?' in type cast`

```
Unhandled exception:
type 'int' is not a subtype of type 'String?' in type cast
#0      _$ProductResultV3FromJson (package:openfoodfacts/src/model/product_result_v3.g.dart:15:33)
#1      new ProductResultV3.fromJson (package:openfoodfacts/src/model/product_result_v3.dart:64:7)
#2      OpenFoodAPIClient.getProductV3 (package:openfoodfacts/src/open_food_api_client.dart:260:25)
<asynchronous suspension>
#3      main (package:openfoodfacts/main.dart:5:29)
<asynchronous suspension>
```

**Comment by monsieurtanuki** [comment]
You need to put `version: ProductQueryVersion.v3` in your configuration.

**Comment by M123-dev** [comment]
Shouldn't we then force the version to v3 in getProductV3

**Comment by M123-dev** [comment]
@monsieurtanuki ?

**Comment by monsieurtanuki** [comment]
> Shouldn't we then force the version to v3 in getProductV3

The "V3" in `getProductV3` doesn't mean the version of the search, but the version of the returned format.

My suggestions:
1. have the `getProductV3` method crash immediately if version < 3
2. make api version a `required` parameter (yes it's a breaking change, but these days we can afford that)
3. possibly deprecate v0, v1 and v2

What do you think of that?

**Comment by M123-dev** [comment]
Sounds good 👍🏼

**Comment by monsieurtanuki** [comment]
> I'd not require this, SDK users shouldn't worry about this, but deprecating the others will solve this problem anyway

I would require the version not out of cruelty, but in order to make obvious that there is a version number and that it means something.
If we deprecate v0, v1 and v2, there are methods that currently use those values as default. It would be "Do as I say, not as I do"! Or we could put v3 as default values for version, but that would mean that the user won't get the same data as before (because of the upgraded version that wasn't an explicit choice).
