### ISSUE TITLE
Add support for `Weight of one empty unit (g)`and `Quantity of product contained per unit`

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-dart#662]
### What
- Add support for `Weight of one empty unit (g)`and `Quantity of product contained per unit`

        > Great for the quick turnaround @monsieurtanuki 👏 Are `Weight of one empty unit (g)`and `Quantity of product contained per unit` causing any issues ?
They are not in off-dart.

_Originally posted by @monsieurtanuki in https://github.com/openfoodfacts/smooth-app/issues/3475#issuecomment-1365939542_

**Comment by monsieurtanuki** [comment]
> Add support for Weight of one empty unit (g)and Quantity of product contained per unit

@stephanegigandet How can we retrieve/set those values from/to the server?

**Comment by stephanegigandet** [comment]
@monsieurtanuki 

for reading, we have the fields in the packagings array: https://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/openfoodfacts/openfoodfacts-server/packagings-api/docs/reference/api-v3.yml#tag/Read-Requests/operation/get-product-by-barcode

<div class="sc-bCwfaz ilMEYI" style="font-size: 0.9em; font-family: Courier, monospace; box-sizing: border-box; -webkit-tap-highlight-color: rgba(255, 255, 255, 0); color: rgb(51, 51, 51); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(250, 250, 250); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Array<span> </span></div><div class="sc-hmbstg gULTOj" style="padding-left: 10px; box-sizing: border-box; -webkit-tap-highlight-color: rgba(255, 255, 255, 0); color: rgb(51, 51, 51); font-family: Roboto, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(250, 250, 250); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">

number_of_units | integerumber of units of this packaging component contained in the product (e.g. 6 for a pack of 6 bottles)
-- | --
shape | object (shape)The shape property is canonicalized using the packaging_shapes taxonomy.
material | object (material)The material property is canonicalized using the packaging_materials taxonomy.
recycling | object (recycling)The recycling property is canonicalized using the packaging_recycling taxonomy.
quantity_per_unit | stringQuantity (weight or volume) of food product contained in the packaging component. (e.g. 75cl for a wine bottle)
quantity_per_unit_value | numberValue parsed from the quantity field.
quantity_per_unit_unit | stringUnit parsed and normalized from the quantity field.
weight_specified | numberWeight (as specified by the manufacturer) of one unit of the empty packaging component (in grams). (e.g. for a 6 pack of 1.5l water bottles, it might be 30, the weight in grams of 1 empty water bottle without its cap which is a different packaging component).
weight_measured | numberWeight (as measured by one or more users) of one unit of the empty packaging component (in grams). (e.g. for a 6 pack of 1.5l water bottles, it might be 30, the weight in grams of 1 empty water bottle without its cap which is a different packaging component).
weight_estimated | numberWeight (as estimated from similar products) of one unit of the empty packaging component (in grams). (e.g. for a 6 pack of 1.5l water bottles, it might be 30, the weight in grams of 1 empty water bottle without its cap which is a different packaging component).
weight | numberWeight of one unit of the empty packaging component.
weight_source_id | stringIndicates which field was used to populate the "weight" field. Either "specified", "measured", or "estimated"

</div><br class="Apple-interchange-newline">

For writing, each packaging component has a weight_measured and quantity_per_unit fields:
https://github.com/openfoodfacts/openfoodfacts-server/blob/main/docs/reference/schemas/packagings/packaging_component-write.yaml

**Comment by monsieurtanuki** [comment]
Thank you @stephanegigandet!
