### ISSUE TITLE
Return images object containing image instead of list of image objects. 

### ISSUE THREAD

**Issue by M123-dev** [openfoodfacts/openfoodfacts-dart#68]
The title is a little confusing but what I mean. When I built my app with off integrated. I was very confused because I got the image url, but this photo was very small / pixelated. After a while I found out that a list of images with different sizes was returned.
At the time it's:

`result.product.images[2].url`

It would be much easier to understand to access the image by calling

`result.product.images.small.url`

**Comment by MohamedFBoussaid** [comment]
@M123-dev do you think this will be solved with @stephanegigandet suggestion here ? https://github.com/openfoodfacts/openfoodfacts-dart/issues/111

**Comment by M123-dev** [comment]
I think this could solve it. My problem when using this plugin was that it was unclear for me what images are in the product.images list. 

It took me a long time to figure out how to get a full-sized one.

**Comment by MohamedFBoussaid** [comment]
Yeah agree, me too I had to add a layer on my app to make it easier eachtime to get the size and type of image needed. 

So once the #111 is solved we can maybe close this one

**Comment by M123-dev** [comment]
Better now #120 #111
