### ISSUE TITLE
[RFC] Support for Open Food Facts variants

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-dart#69]
Request for comments: 
Is there any way to add support for Open Food Facts variants such as ?

- Open Beauty Facts - https://world.openbeautyfacts.org/
- Open Pet Food Facts - https://world.openpetfoodfacts.org/
- Open Products Facts - https://world.openproductsfacts.org/

Is there a way to do it that would not break existing apps ? Or would we need to clone the package ?

**Comment by monsieurtanuki** [comment]
@teolemon We now have a `ServerType` enum that would be helpful:
```dart
/// Type of Server (e.g. "food facts", "beauty facts", ...).
enum ServerType implements OffTagged {
  /// Open Food Facts
  openFoodFacts(offTag: 'off'),
  /// Open Beauty Facts
  openBeautyFacts(offTag: 'obf'),
  /// Open Pet Food Facts
  openPetFoodFacts(offTag: 'opff'),
  /// Open Product Facts
  openProductFacts(offTag: 'opf');
  const ServerType({
    required this.offTag,
  });
  @override
  final String offTag;
}
```

In off-dart this is how we compute the URLs:
```dart
        host: OpenFoodAPIConfiguration.getQueryType(queryType) == QueryType.PROD
            ? OpenFoodAPIConfiguration.uriProdHost // for the moment, 'world.openfoodfacts.org'
            : OpenFoodAPIConfiguration.uriTestHost, // for the moment, 'world.openfoodfacts.net'
```
We could add a `ServerType` parameter to get an easy access to other servers

I don't think it makes much sense maintaining two variables for the host (`uriProdHost`, `uriTestHost`) as nobody uses both at the same time.
I guess we would be better off with one variable (e.g. `host`) and 2 methods:
* `setForcedHost(final String host)` that would force the host to a specific value - e.g. for custom servers
* `setHost(final QueryType queryType, final ServerType serverType)` for "normal" use - e.g. I'm using open beauty facts on PROD

That would mean a (minor) breaking change.

**Comment by monsieurtanuki** [comment]
Actually we can already point to open beauty facts today by changing `OpenFoodAPIConfiguration.uriProdHost`.
Would beauty product data fit in a food product data template? Probably not, and we need specs for that.

**Comment by monsieurtanuki** [comment]
@teolemon As long as products have the same structure in all servers, yes we can.
