### ISSUE TITLE
Update HTTP Library 

### ISSUE THREAD

**Issue by Maxmontgelas** [openfoodfacts/openfoodfacts-dart#735]
You need to update the http Library

**Comment by monsieurtanuki** [comment]
@Maxmontgelas We don't _need_ to upgrade the http library.
We're currently using `http: ^0.13.5`, and a new version of `http` (`1.0.0`) was released last week, with that [change log](https://pub.dev/packages/http/changelog):
* Requires Dart 3.0 or later.
* Add base, final, and interface modifiers to some classes.

Doesn't look like a massive improvement, and the main flutter project of openfoodfacts (https://github.com/openfoodfacts/smooth-app/) hasn't upgraded to flutter 3.10 / dart 3.0 yet (cf. https://github.com/openfoodfacts/smooth-app/issues/3953)

**Comment by Maxmontgelas** [comment]
Of course you should be upgrading keeping all up to date. What a strange reply.

**Comment by M123-dev** [comment]
Ok, we don't need to, but eventually we will. As monsieurtanuki pointed out, the main app for which this package is developed (https://github.com/openfoodfacts/smooth-app) isn't upgraded to flutter 3.7 just now so we'll have to postphone that.

Now the question is, what is stopping you (the intention behind this issue) @Maxmontgelas. 

1. Do you need a feature of `http 1.0.0` if so you'll likely have to use a fork of this package for now
2. Do you have some package conflicts, if so you can likely solve them using package overrides

**Comment by Maxmontgelas** [comment]
It all works fine for myself as I've made appropriate adjustments. But one should not need to do adjustments as it's not so complicated or time consuming to update this here.

**Comment by marcelweigle** [comment]
The main reason to upgrade the HTTP dependency is that multiple other librarys depend on HTTP and therefor we can not upgrade our other dependencies. In my case i cannot upgrade google_fonts and typesense.

So this is kinda important and would be appreciated

**Comment by Maxmontgelas** [comment]
You can use override but it's just a shame must do that.

**Comment by monsieurtanuki** [comment]
Will be taken care of in #764.
