### ISSUE TITLE
Allow to fetch robotoff questions by insight_type for a given product 

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-dart#740]
### Why - Problem description
- Allowing us to add 🎯 robotoff questions inside various editing sections in the Mobile app 

### What - Proposed solution
- Allow to fetch robotoff questions by insight_type for a given product

**Comment by monsieurtanuki** [comment]
@teolemon Maybe I miss something here but I think we already got it:
* fetch all the questions related to a barcode
* loop on the questions and check each question insight type

If so, we don't really need an extra method in off-dart and Smoothie is not blocked, right?

**Comment by teolemon** [comment]
- For a given barcode, we can indeed do that Smoothie side 👍 
- insight_type is otherwise useful as a filter in bulk mode, very much like country

**Comment by monsieurtanuki** [comment]
Done in #748.
