### ISSUE TITLE
Robotoff: add the "server type" parameter (off, obf, ...)

### ISSUE THREAD

**Issue by monsieurtanuki** [openfoodfacts/openfoodfacts-dart#742]

**Comment by monsieurtanuki** [comment]
@raphael0202 Playing with the "country" parameter, we're a bit stuck.
Our typical country parameters are more country code (`'fr`') than country tags (`'en:france'`).
Is there a way you could add a country code parameter instead of a country tag parameter, for instance in https://openfoodfacts.github.io/robotoff/references/api/#tag/Questions/paths/~1questions/get ?
The other solution for us in off-dart would be to maintain a repository of country tags, which stinks a bit.

**Comment by teolemon** [comment]
off-pro is the producer platform. Unless we do in the future a version of the app for producers allowing them to play hunger games on their private pre-prod space, that does not make any sense.
Doing so would also require an org id I believe.

**Comment by monsieurtanuki** [comment]
Closed by #743.

**Comment by raphael0202** [comment]
@monsieurtanuki  Sorry for the delay, I didn't see this mention. Yes we can add a country code to Robotoff API instead of country ID such as en:france. Can you open an issue on Robotoff repository?
