### ISSUE TITLE
Product.dart does not convert packagings correctly to JSON

### ISSUE THREAD

**Issue by peterwvj** [openfoodfacts/openfoodfacts-dart#752]
### Description

Conversion of `Product` objects to JSON fails to generate valid JSON for the `packagings` field when this list/field contains `ProductPackaging` objects. In this case, the output generated using the `Product.toJson` function is invalid JSON and `Product` objects cannot be restored from this JSON using the `Product.fromJson` function. 

### Expected behavior

The following test should pass (but currently it does not with version 2.6.0 of the SDK).

```dart
import 'package:flutter_test/flutter_test.dart';
import 'package:openfoodfacts/openfoodfacts.dart';

void main() {
  test('ProductPackaging bug', () {
    final testProduct = Product();
    const productName = 'Orange';
    testProduct.productName = productName;
    testProduct.packagings = [ProductPackaging()..quantityPerUnit = '75cl'];
    final productJson = testProduct.toJson();
    try {
      final productRestored = Product.fromJson(productJson);
      expect(productRestored.productName, productName);
    } catch (e, s) {
      print(s);
      fail('Could not restore Product from JSON ${e.toString()}');
    }
  });
}

```

### Stacktraces
If applicable, provide error stacktraces.

```
#0      new ProductPackaging.fromJson (package:openfoodfacts/src/model/product_packaging.dart:53:34)
#1      _$ProductFromJson.<anonymous closure> (package:openfoodfacts/src/model/product.g.dart:119:41)
#2      MappedListIterable.elementAt (dart:_internal/iterable.dart:415:31)
#3      ListIterator.moveNext (dart:_internal/iterable.dart:344:26)
#4      new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189:27)
#5      new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
#6      new List.of (dart:core-patch/array_patch.dart:47:28)
#7      ListIterable.toList (dart:_internal/iterable.dart:214:7)
#8      _$ProductFromJson (package:openfoodfacts/src/model/product.g.dart:120:12)
#9      new Product.fromJson (package:openfoodfacts/src/model/product.dart:535:28)
#10     main.<anonymous closure> (file:///home/peter/git/fit/fitness_tracker/test/product-bug_test.dart:12:39)
#11     Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:215:19)
<asynchronous suspension>
#12     StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:124:15)
<asynchronous suspension>
```

### Package information
Open Food Facts package version: 2.6.0

**Comment by monsieurtanuki** [comment]
@peterwvj I'll have a look a it.

**Comment by monsieurtanuki** [comment]
@peterwvj I don't know how satisfactory it could be, but this is how you could "fix" the bug:
```dart
  test('ProductPackaging bug', () {
    final testProduct = Product();
    const productName = 'Orange';
    testProduct.productName = productName;
    testProduct.packagings = [ProductPackaging()..quantityPerUnit = '75cl'];
    final productJson = testProduct.toJson();

    final String jsonString = jsonEncode(productJson); // HERE

    try {

      final productRestored =
          Product.fromJson(jsonDecode(jsonString) as Map<String, dynamic>); // and HERE

      expect(productRestored.productName, productName);
    } catch (e, s) {
      print(s);
      fail('Could not restore Product from JSON ${e.toString()}');
    }
  });
```

Not sure why it works with the json encode/decode steps.
But it does work in Smoothie anyway: for our background tasks we have to encode/decode products into strings.

Feel free to close the issue if relevant.

**Comment by peterwvj** [comment]
@monsieurtanuki thanks for looking into this and sorry for not getting back any sooner.

I think the problem is the JSON generation of the `packagins` fields. After looking a bit more into this, I tried assigning a "toJson" conversion function to the `packagings` field and that made the test pass. This approach is similar to the way JSON conversion is implemented for the `ingredients` fields (which is also implemented using a `List`).

After adding the proposed fix, I did run into some issues regenerating the *.g.dart files using `build_runner` but I managed to fix that by upgrading the SDK dependencies according to the instructions [here](https://github.com/dart-lang/build/issues/3519#issuecomment-1587514460).

I pushed my changes to the branch [peterwvj/issue-752](https://github.com/openfoodfacts/openfoodfacts-dart/commit/7e48afe844f36190ac96081dc2d184983776907e). Could you take a look and let me know what you think?
