### ISSUE TITLE
Add product_name_brand_quantity function

### ISSUE THREAD

**Issue by ductung-bfast** [openfoodfacts/openfoodfacts-dart#773]
### Why - Problem description
Mobile app has no such full name as on the web.

### What - Proposed solution
We should replicate product_name_brand_quantity function as on the web

**Comment by teolemon** [comment]
- For reference https://github.com/openfoodfacts/openfoodfacts-server/blob/0234c56635292483cd397aa5893610be39f256b9/lib/ProductOpener/Products.pm#L2679
- @stephanegigandet any comments on this one ?

**Comment by stephanegigandet** [comment]
Is is a good idea I think
