### ISSUE TITLE
tracesTagsInLanguages always empty

### ISSUE THREAD

**Issue by FantaMagier** [openfoodfacts/openfoodfacts-dart#819]
### Description
I want to use the tracesTagsInLanguages Function but every language from the Map is null and not existing. The normal tracesTags is working.

### Expected behavior

```dart
 var traces = product?.tracesTagsInLanguages?[OpenFoodFactsLanguage.GERMAN] ?? [];
```
should give the Traces for German

### Stacktraces
No Errors

### Package information
Open Food Facts package version: openfoodfacts: ^3.1.0

### Additional context
Example Product: https://de-en.openfoodfacts.org/product/7613036042000/buchstaben-suppe-maggi

**Comment by monsieurtanuki** [comment]
Hi @FantaMagier!

I assume there's something wrong in your code, as we already test that in our unit tests.

For instance:
```dart
      const String barcode = '7613036042000';
      const List<OpenFoodFactsLanguage> languages = [
        OpenFoodFactsLanguage.ENGLISH,
        OpenFoodFactsLanguage.GERMAN,
      ];

      final ProductQueryConfiguration configurations =
          ProductQueryConfiguration(
        barcode,
        languages: languages,
        fields: [
          ProductField.TRACES_TAGS_IN_LANGUAGES,
        ],
        version: ProductQueryVersion.v3,
      );
      final ProductResultV3 result = await OpenFoodAPIClient.getProductV3(
        configurations,
      );
      final Product product = result.product!;
      print('traces: ${result.product!.tracesTagsInLanguages}');
```
will display:
`traces: {OpenFoodFactsLanguage.GERMAN: [Eier, Milch, Senf, Soja], OpenFoodFactsLanguage.ENGLISH: [Eggs, Milk, Mustard, Soybeans]}`
