### ISSUE TITLE
Some small fails

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-dart#825]
❌ test/api_search_products_test.dart: OpenFoodAPIClient search products query potatoes products (failed)
  Expected: <24>
    Actual: <0>
  
  package:matcher                           expect
  test/api_search_products_test.dart 785:7  main.<fn>.<fn>

❌ test/api_get_user_products_test.dart: OpenFoodAPIClient get user products contributor (failed)
  Expected: <6>
    Actual: <5>
  (OpenFoodFactsLanguage.ENGLISH, TagFilterType.CREATOR)
  
  package:matcher                             expect
  test/api_get_user_products_test.dart 54:7   main.<fn>.getCount
  ===== asynchronous gap ===========================
  test/api_get_user_products_test.dart 75:27  main.<fn>.getCountForAllLanguages
  ===== asynchronous gap ===========================
  test/api_get_user_products_test.dart 95:25  main.<fn>.checkTypeCount

**Comment by monsieurtanuki** [comment]
@teolemon As far as off-dart goes, those tests don't fail anymore.
And there are already related issues on the server side: https://github.com/openfoodfacts/openfoodfacts-server/issues/9279 https://github.com/openfoodfacts/openfoodfacts-server/issues/9278

**Comment by teolemon** [comment]
ok, closing @monsieurtanuki
