### ISSUE TITLE
Cannot login with a non-ASCII username

### ISSUE THREAD

**Issue by monsieurtanuki** [openfoodfacts/openfoodfacts-dart#829]
cf. https://github.com/openfoodfacts/smooth-app/issues/4813
cf. https://openfoodfacts.sentry.io/issues/3458725816/?project=5376745&referrer=github_integration
Managed to reproduce the issue trying to connect (`login2`) as `User(userId: 'លីវយី', password: '123')`

Looks like the problem comes from `From` (haha) in the http header.
It's expected to be an email address (cf. https://datatracker.ietf.org/doc/html/rfc9110#name-from).
But we put there the user name.

Looks like only ASCII or ISO-8859-1 are 100% expected to work.

**Comment by g123k** [comment]
Correct me if I'm wrong, but it's more like a server issue than a Dart one?

**Comment by monsieurtanuki** [comment]
> Correct me if I'm wrong, but it's more like a server issue than a Dart one?

I don't think so, because WE are sending a header that is an INVALID http header, regardless of the server.
That said, there may be an impact on the off server side depending on the way they need/use `From`.
@teolemon @stephanegigandet do you guys need that `From`, e.g. for your stats, and would a base64 version of the `From` be good enough for you?

**Comment by monsieurtanuki** [comment]
Fixed by #830.
