### ISSUE TITLE
Nutriment : PerSize.serving Potentially Broken

### ISSUE THREAD

**Issue by davidpryor** [openfoodfacts/openfoodfacts-dart#872]
### Description
When setting Nutriments to `PerSize.serving`, `Product.servingSize`, and `Product.nutrimentDataPer` to `PerSize.serving.offTag`. The server will not save the Nutriments. When I set the `PerSize` to `oneHundredGrams`, the server will accept it and properly scale it based on my `servingSize` attribute.

### Expected behavior
SDK/backend should accept Nutriments provided in `PerSize.serving`.

### Stacktraces
None

### Package information
Open Food Facts package version: 3.3.2

### Additional context
I see there is a test that sends a new food to the backend with `PerSize.serving`, but this test sends empty nutriments, so this particular scenario is not tested with the SDK (I think 😁 )

**Comment by monsieurtanuki** [comment]
Hi @davidpryor!
Please write a unit test that fails according to you.

**Comment by davidpryor** [comment]
@monsieurtanuki 
I have created a test here:
https://github.com/davidpryor/openfoodfacts-dart/commit/83e96dcc54cf69eb29871cd9ea28c762129c6a88

This was a copy of an existing test with the following changes:
```diff
-      const PerSize perSize = PerSize.oneHundredGrams;
+      const PerSize perSize = PerSize.serving;
```
```diff
-      final String nutrimentDataPer = PerSize.oneHundredGrams.offTag;
+      final String nutrimentDataPer = PerSize.serving.offTag;
```
```diff
        final Product newProduct = Product(
          barcode: BARCODE,
          productName: PRODUCT_NAME,
          nutrimentDataPer: nutrimentDataPer,
+          servingSize: "20g",
+          servingQuantity: 20,
          nutriments: nutriments,
        );
```
These fields on Product were communicated to me by Alex on slack https://openfoodfacts.slack.com/archives/C032PK9D8/p1706546238737309?thread_ts=1706301302.772189&cid=C032PK9D8


Here is the first incorrect expect check:
<img width="499" alt="image" src="https://github.com/openfoodfacts/openfoodfacts-dart/assets/79552751/acfde590-2e30-4aef-88b3-fd391ff2a5a4">

**Comment by davidpryor** [comment]
I think I have discovered what is happening.
@stephanegigandet has clarified `nutriments_(nutrient)_100g` and `nutriments_(nutrient)_serving` are both read only and the server only cares about `nutrition_data_per` for writes.

The issue is that when the SDK preps the nutriments for the server, it looks specifically for the suffix "_100g" and removes it. This leads to the nutriments only properly being prepared in the `nutriments_(nutrient)` field when the you `setValue` with PerSize.oneHundredGrams.

I think the fix here is to strip both `PerSize.serving.offTag` and `PerSize.oneHundredGrams.offTag` when serializing for a write.

I think the ultimate fix is to remove the need for send PerSize to the `setValue` method at all since it isn't technically used to control a write. This would be a breaking change, but I think ultimately, this would be the least confusing approach for a user.

I would be happy to make a PR with the change if you agree.
