### ISSUE TITLE
Robotoff tests are failing

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-dart#880]
> Tests are failing @monsieurtanuki (and we're in the Open Prices call right now ;-) https://meet.google.com/oin-hiqp-tmd )

Robotoff tests are failing, indeed.
![Screenshot_20240207_150731_Chrome](https://github.com/openfoodfacts/openfoodfacts-dart/assets/11576431/493a9567-02b4-4c42-90c7-c54e0e323100)

_Originally posted by @monsieurtanuki in https://github.com/openfoodfacts/openfoodfacts-dart/issues/855#issuecomment-1932127957_

**Comment by teolemon** [comment]
@raphael0202

**Comment by monsieurtanuki** [comment]
Does not happen anymore.
