### ISSUE TITLE
Get a localized list of countries

### ISSUE THREAD

**Issue by monsieurtanuki** [openfoodfacts/openfoodfacts-dart#890]
### Why - Problem description
cf. https://github.com/openfoodfacts/smooth-app/issues/4921
In Smoothie we use a [package](https://pub.dev/packages/iso_countries) in order to localize the country names.
This package is only available for iOS and Android (not linux, macOS, web, windows).
And on the server we can retrieve localized countries, with https://world.openfoodfacts.org/cgi/countries.pl?lc=de

### What - Proposed solution
We should be able to use the server to localize country names.
Something like that:
```dart
  static Future<Map<OpenFoodFactsCountry, String>> getLocalizedCountries(
    final OpenFoodFactsLanguage language, {
    final UriProductHelper uriHelper = uriHelperFoodProd,
  }) async { //...
```

### Additional context
That could also be a good opportunity to check if some countries are missing in `OpenFoodFactsCountry.values`.

**Comment by shubhsardana29** [comment]
Are there any specific considerations or requirements regarding how the localized country names should be handled in cases where there might be discrepancies or inconsistencies between the data provided by the server and the expected country names within the application's context?

**Comment by monsieurtanuki** [comment]
@shubhsardana29 We just want to return a map of OpenFoodFactsCountry and String. We have no expectations regarding the localizations.
In the process, we may find unexpected countries: just report them and we'll see later what to do with them (e.g. we may not need Yugoslavia in 2024).

**Comment by monsieurtanuki** [comment]
@shubhsardana29 Feel like starting to code? No hard sell.

**Comment by monsieurtanuki** [comment]
@shubhsardana29 Too late ;)
