### ISSUE TITLE
Allow to change host for product search

### ISSUE THREAD

**Issue by goerlitz** [openfoodfacts/openfoodfacts-dart#907]
I'm using following code for product search:

```dart
SearchResult result = await OpenFoodAPIClient.searchProducts(
  null,
  configuration,
  uriHelper: const off.UriProductHelper(domain: 'openfoodfacts.org'),
);
```

Now, I would like to search only for products in Germany (de.openfoodfacts.org), but the [UriProductHelper](https://github.com/openfoodfacts/openfoodfacts-dart/blob/d6adb488626baaf3a1396d8693cbe0d3efaa3987/lib/src/utils/uri_helper.dart#L103) has hardcoded `world` as subdomain in its constructor.

```dart
const UriProductHelper({
  required this.domain,
  super.scheme = 'https',
  super.isTestMode = false,
  this.userInfoForPatch,
  super.defaultAddUserAgentParameters = true,
}) : super(host: 'world.$domain');
```

It is actually bad practice to hard code things like that - it totally prevents instantiating `UriProductHelper` with a different subdomain. Instead the subdomain value should be configurable.

I would suggest an easy fix like this:

```dart
const UriProductHelper({
  required this.domain,
  this.subdomain = 'world',
  super.scheme = 'https',
  super.isTestMode = false,
  this.userInfoForPatch,
  super.defaultAddUserAgentParameters = true,
}) : super(host: '$subdomain.$domain');
```

**Comment by monsieurtanuki** [comment]
Hi @goerlitz!
To restrict your search to a country, please use the `final OpenFoodFactsCountry? country` parameter of `AbstractQueryConfiguration`.
cf. test file `api_search_products_test.dart`:
```dart
        final SearchResult result = await OpenFoodAPIClient.searchProducts(
          TestConstants.PROD_USER,
          ProductSearchQueryConfiguration(
            parametersList: parameters,
            fields: [ProductField.BARCODE],
            language: OpenFoodFactsLanguage.FRENCH,
            country: OpenFoodFactsCountry.FRANCE,
            version: version,
          ),
        );
```

I don't know if creating/using 100+ subdomains, one for each country, is a best practice either, especially for an API.
For the record we also use `robotoff.openfoodfacts.org`, `api.folksonomy.openfoodfacts.org` and `events.openfoodfacts.org`. Using a URL parameter to restrict to a country seems therefore more appropriate, doesn't it?

Regarding your code suggestion, I don't say it wouldn't work, but it looks like we don't need it eventually, and I'm not keen on adding code "just in case". Unless you find use cases where we would need it.

Feel free to close the issue if relevant.

**Comment by goerlitz** [comment]
Hi @monsieurtanuki ,
thanks for the quick reply.
Actually, I did not realize that there is a country parameter in the configuration object. I'm so used to using the country subdomain for restricting the results.

Please not that there already exists a subdomain for each country. Hence, I find it a bit confusing that you could either use the subdomain or the query parameter to restrict the country.

![off_country_subdomain](https://github.com/openfoodfacts/openfoodfacts-dart/assets/2389436/8d14e01d-a520-4490-ba00-ef4ae65397d4)

**Comment by goerlitz** [comment]
Closing the issue because the `country: OpenFoodFactsCountry.FRANCE` does exactly what I wanted to do via the subdomain.

**Comment by monsieurtanuki** [comment]
@goerlitz Yeah I know, both subdomain and URL parameter work, but we've been told months ago to rather switch to URL parameter for the API calls (that probably avoids some unnecessary URL redirections).
I guess subdomains do make more sense for the website, with mainstream visitors.
Glad I helped.

**Comment by goerlitz** [comment]
@monsieurtanuki I discovered an issue with the languages.

If I use the subdomain, the server will automatically set the default language for the country.
Therefore, this query
https://de.openfoodfacts.org/api/v2/product/20101268?fields=image_url
will return
`"image_url": "https://images.openfoodfacts.org/images/products/20101268/front_de.196.400.jpg"`

Whereas, when using `cc=de`
https://world.openfoodfacts.org/api/v2/product/20101268?cc=de&fields=image_url
the language is automatically set to English and I will get a different result (which I don't want).
`"image_url": "https://images.openfoodfacts.org/images/products/20101268/front_en.165.400.jpg"`

Typically, I don't know which country the app user selects, but I need to make sure that the appropriate default language for that country is used.

Question: how can I determine the correct default language for any given country to put it in the configuration?

**Comment by monsieurtanuki** [comment]
> Question: how can I determine the correct default language for any given country to put it in the configuration?

Answer: there's no such thing as the default language for any given country (e.g. Belgium).
I would strongly recommend you to set both country and language parameters.
Side note: on the server side they probably have a country=>language map in order to know that in Germany they speak German (e.g. for the `de` subdomain) but we have no reason to implement it / duplicate it in dart. Please have a look at the server code if you really need it.

**Comment by goerlitz** [comment]
Okay, thanks.
