### ISSUE TITLE
Why are we still referencing v0 ?

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-dart#927]
### Description 
- Why are we still referencing v0 ?
- https://github.com/openfoodfacts/openfoodfacts-dart/blob/master/lib/src/utils/product_query_configurations.dart#L18
- We're getting blasted by those queries, they could at least be v1 or v2 :-) 
```
xxxx - - [14/May/2024:16:11:37 +0000] "GET /cgi/display.pl?api/v0/product/8710496979101.json HTTP/1.0" 200 21111 "-" "Dart/3.2 (dart:io)" 0/15392
xxxx - - [14/May/2024:16:11:38 +0000] "GET /cgi/display.pl?api/v0/product/8710496979101.json HTTP/1.0" 200 21113 "-" "Dart/3.2 (dart:io)" 0/11536
xxxxx - - [14/May/2024:16:11:38 +0000] "GET /cgi/display.pl?api/v0/product/8710496979101.json HTTP/1.0" 200 21113 "-" "Dart/3.2 (dart:io)" 0/13177
xxxxx - - [14/May/2024:16:1
```

**Comment by monsieurtanuki** [comment]
> Why are we still referencing v0 ?

Because `v0` has a specific URL builder. 
```dart
  String getPath(final String barcode) {
    if (version == 0) {
      return '/api/v0/product/$barcode.json';
    }
    return '/api/v$version/product/$barcode/';
  }
```

> We're getting blasted by those queries, they could at least be v1 or v2 :-)

We can change that by removing `0` as a possible value (minor breaking change), or silently upgrading it to `2`.
Do you have a preference?

**Comment by teolemon** [comment]
@stephanegigandet

**Comment by stephanegigandet** [comment]
We can upgrade to v2 if all the tests still pass
