### ISSUE TITLE
Add missing ADDITIVES_TAGS_IN_LANGUAGES and ALLERGENS_TAGS_IN_LANGUAGES

### ISSUE THREAD

**Issue by goerlitz** [openfoodfacts/openfoodfacts-dart#928]
### Why - Problem description
Currently, it is not possible to execute following API request because in [ProductField](https://github.com/openfoodfacts/openfoodfacts-dart/blob/master/lib/src/utils/product_fields.dart) the required
`ADDITIVES_TAGS_IN_LANGUAGES` and `ALLERGENS_TAGS_IN_LANGUAGES` field definitions are missing.

https://de.openfoodfacts.org/api/v2/product/20101268?fields=additives_tags_de,additives_tags_en,allergens_tags_de,allergens_tags_en

Moreover, the existing `ADDITIVES(offTag: 'additives_tags')` and `ALLERGENS(offTag: 'allergens_tags')` do not follow the existing naming convention - they should be named `ADDITIVES_TAGS` and `ALLERGENS_TAGS`.

### What - Proposed solution
Add `ADDITIVES_TAGS_IN_LANGUAGES` and `ALLERGENS_TAGS_IN_LANGUAGES` and the logic to handle these fields properly.

**Comment by goerlitz** [comment]
@monsieurtanuki I just implemented the feature. Would be great if you can have a look.

**Comment by monsieurtanuki** [comment]
Fixed in #929.
