### ISSUE TITLE
Allow to get ingredient OCR output

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-dart#93]
Open Food Facts uses optical character recognition (OCR) to retrieve nutritional data and other information from the product labels.

Process

- [x] Capture the barcode of the product where you want to perform the OCR.
- [x] The Product Opener server software opens the image (process_image=1)
- [x] Product Opener returns a JSON response. Processing is done using Tesseract or Google Cloud Vision (recommended). The result is often cripped with errors with Tesseract, less with Google Cloud Vision.

Notes: * The OCR may contain errors. Encourage your users to correct the output using the ingredients WRITE API. * You can also use your own OCR, especially if to plan to send a high number of queries.

Parameters
Test server: https://world.openfoodfacts.org/cgi/ingredients.pl
code=code
id=imagefield
process_image=1

**Comment by MohamedFBoussaid** [comment]
@teolemon, for the id parameter this will be only for ingredients ? (ingredients_en, ingredients_fr, ingredients_de ...) or it can be something else? an if we don't set the ocr_engine parameter this will use automatically the Google Cloud Vision, or it should be specified in all cases?

**Comment by MohamedFBoussaid** [comment]
Implemented with #94

**Comment by MohamedFBoussaid** [comment]
Closed the issue by mistake. 
@teolemon can you please confirm that we can close the issue. 
Thanks.

**Comment by teolemon** [comment]
yes of course
