### ISSUE TITLE
Prices/Location: add countrycode field.

### ISSUE THREAD

**Issue by monsieurtanuki** [openfoodfacts/openfoodfacts-dart#933]
### Why - Problem description
Prices / Location now provides a "countrycode" field, and this field is helpful for us, so let's integrate it!
https://github.com/openfoodfacts/open-prices/pull/296

**Comment by raphodn** [comment]
fyi the field name is `osm_address_country_code`

And there's also 2 new extra fields : `osm_tag_key` & `osm_tag_value` : https://github.com/openfoodfacts/open-prices/pull/294
