### ISSUE TITLE
Flutter Web and the User Agent

### ISSUE THREAD

**Issue by g123k** [openfoodfacts/openfoodfacts-dart#937]
Hi everyone,

I have received several complaints about the SDK when used on the web.
Every time the error is `ClientException: XMLHttpRequest error.`.

After digging a little bit, the real Exception is:
`Refused to set unsafe header "User-Agent"` 

Today, the way we send the custom header on mobile and desktop is OK.
However, on the web, a User-Agent must follow a [strict format](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent).

So we have two choices here:
- Try to create a valid header entry
- Rename what we call "User-Agent" to another name

**Comment by monsieurtanuki** [comment]
@g123k AFAIR the user-agent is used by the OFF server for stats, so any change would have an impact on the server stats, cc @stephanegigandet 
IMHO the easiest solution would be not to force the user-agent when used in web mode. I assume that the browser user-agent will overwrite that void, which would be a relatively relevant approximation for the OFF server. Or it will be kept null, which would also solve the current issue.
Btw we can easily detect "web" usage, we already do with code like that  - we consider the "js" version as "web":
```dart
import 'uri_reader_stub.dart'
    if (dart.library.io) 'uri_reader_io.dart'
    if (dart.library.js) 'uri_reader_js.dart';
```
Just my 2 cents.
