### ISSUE TITLE
Price proof: link a date, location & currency

### ISSUE THREAD

**Issue by monsieurtanuki** [openfoodfacts/openfoodfacts-dart#942]
@monsieurtanuki in the next few days i will focus on integrating these new Proof fields.
- the UI will change a bit, we'll be asking first the proof data, and then allow adding prices (slightly more proof-oriented)
- if a user selects an existing proof with these info, the form will be pre-filled (and the fields set as readonly)
- new info will be displayed under each proof, and possibility to order & filter as well
- futur step will be to send these proofs to https://github.com/openfoodfacts/open-prices/issues/320 and get extra data (and one day pre-fill these info automatically)

_Originally posted by @raphodn in https://github.com/openfoodfacts/open-prices-frontend/issues/634#issuecomment-2178706438_

**Comment by monsieurtanuki** [comment]
@raphodn I've just tried to _update_ a proof, and I got the following error message. Any idea what's wrong with my call?
```json
{
  "detail":[
    {
      "type":"extra_forbidden",
      "loc":["body","app_name"],
      "msg":"Extra inputs are not permitted",
      "input":"off-dart integration tests",
      "url":"https://errors.pydantic.dev/2.6/v/extra_forbidden"
    }
  ]
}
```

**Comment by raphodn** [comment]
> I've just tried to update a proof, and I got the following error message. Any idea what's wrong with my call?

From what i see the server expects a strict list of items in the body. Do you always pass `app_name` in the body ? vs just in the url params instead ? The fields expected for the proof update endpoint are currently : `type`, `currency`, `date`. https://github.com/openfoodfacts/open-prices/blob/67f0d0b58ef639cc65fd8b028c695cf831937ee6/app/schemas.py#L225

**Comment by monsieurtanuki** [comment]
Thank you @raphodn for your answer, now it's solved!

**Comment by raphodn** [comment]
What's still missing is to be able to update the proof's location. I need some thoughts on this first...

**Comment by monsieurtanuki** [comment]
> What's still missing is to be able to update the proof's location. I need some thoughts on this first...

I don't see the problem at all, actually. It's just some other fields.
You mean UX-wise?

**Comment by raphodn** [comment]
Also in terms of fields. We currently ask for la `location_osm_id` and `location_osm_type`, and then link it to an actual location object (and set the `location_id`.

Not sure if this maintainable in the long run. I'll see :)

**Comment by monsieurtanuki** [comment]
Anyway you already have to deal with incoherences, e.g.:
* proof currency and prices currencies
* setting a locationOSMId but no locationOSMType (or one that doesn't match)
* for locations, you can say that the priority is locationId (if passed as an argument), and locationOSM* then if relevant

**Comment by raphodn** [comment]
True, but the incoherences would only come from non-web-or-mobile users (that use the API). And for them we could start enforcing data quality rules

**Comment by monsieurtanuki** [comment]
Indeed.

Btw I've just tried to create a price with a value for price_per (never tried before), and the value doesn't seem to be set (it is null).
It works with updatePrice, though.
Could you have a look at it?

**Comment by raphodn** [comment]
What value did you try for `price_per` ? the 2 valid options are `UNIT` or `KILOGRAM`. https://github.com/openfoodfacts/open-prices/blob/6d3c84ddf10116a98ad6db146a3c51eee60ad89f/app/enums.py#L26
And there's also a validator that sets this value to null if the price has a product (as its only for non-barcode prices). https://github.com/openfoodfacts/open-prices/blob/6d3c84ddf10116a98ad6db146a3c51eee60ad89f/app/schemas.py#L417

**Comment by monsieurtanuki** [comment]
@raphodn Understood now that price_per is only for non-barcodes, thanks!
Then, there's a little bug in your _update_ checks, as I managed to _update_ a price_per for a barcode product.

**Comment by raphodn** [comment]
Oh yeah I see the problem, we only do the validation on create, not update :facepalm:

**Comment by raphodn** [comment]
ok @monsieurtanuki I did some quick changes in the backend here : https://github.com/openfoodfacts/open-prices/pull/342
- rearchitectured the price schemas
- have a basic validation check on price update (but it doesn't solve the `price_per` case you mentioned)
- it now returns an error if extra fields are passed :warning: 

Doing some fixes in the frontend to reflect this : https://github.com/openfoodfacts/open-prices-frontend/pull/668

**Comment by monsieurtanuki** [comment]
@raphodn I've just re-run our 17 off-dart tests about prices, and they all pass.
All the "write" tests work on TEST `.net` env.
As long as you've added optional parameters for existing methods, that should be fine.

**Comment by raphodn** [comment]
Ok awesome, I'll deploy then, so that if there is any issue I can fix it tonight or tomorrow :pray:

**Comment by monsieurtanuki** [comment]
@raphodn LGTM: I've just added a receipt today with Smoothie (without changing anything in the code)
https://prices.openfoodfacts.org/app/users/monsieurtanuki

**Comment by raphodn** [comment]
On the "location update" subject I just created an issue, will work on it in the coming hours/days : https://github.com/openfoodfacts/open-prices/issues/346

**Comment by monsieurtanuki** [comment]
@raphodn I think you should systematically update the proof location/currency/date from the first price, if empty.
I've just had at look at today's proof, and the "missing fields" effect doesn't look good.
![Screenshot_20240628_220925_Chrome](https://github.com/openfoodfacts/openfoodfacts-dart/assets/11576431/357e379c-3b57-4613-a8f3-51755351ffdb)

**Comment by raphodn** [comment]
Well the idea is that the location, date & currency of a proof should be mandatory.
I didn't implement it that way (yet) because there are proofs without prices.
But in the web app you have to provide these 3 info if you want to add a price afterwards (and there's indeed a bug/limitation if you choose an existing proof without these info)

**Comment by raphodn** [comment]
These new fields are optional because some proofs (like GDPR) may have multiple locations & dates. But the idea is that they should be mandatory for PRICE_TAG & RECEIPT proofs..

**Comment by monsieurtanuki** [comment]
> Your screenshot is a proof uploaded from mobile i presume ?

The screenshot was taken on a mobile, from the web app.
The related data came from Smoothie, as the test I ran yesterday.

> Do you plan on implementing these new fields at the proof level ?

First the code in dart has to be reviewed, approved and merged, then it will be easy to integrate in Smoothie/ flutter.

> It would be the best workflow don't you think ?

Don't trust anyone who uses the API, by default.
Like our discussion about you accepting images as `.bin` because the mime header was not set. The solution there was to add a mandatory mime type parameter, if I remember well.

> These new fields are optional because some proofs (like GDPR) may have multiple locations & dates. But the idea is that they should be mandatory for PRICE_TAG & RECEIPT proofs..

Then I would recommend considering GDPR so different from receipt/price tags than they deserve a different API entry point.

> Will implement these validation rules ASAP

Please don't! Smoothie wouldn't work anymore.
Or do it as `api/v2`.

**Comment by raphodn** [comment]
> Please don't! Smoothie wouldn't work anymore.

Then how should we proceed ? This is an evolution that was validated collectively in the Wednesday meeting 10 days ago. And we pushed back the mobile launch considering it (having a proof location, date & currency) was needed to increase data quality and simplifying user input. cc @teolemon

**Comment by monsieurtanuki** [comment]
I wasn't aware of those decisions.
I assumed that an `api/v2` version would do the trick: letting "old" users work without errors with v1 (though deprecated) and letting up-to-date users setting better quality data.
If we're supposed to be in such an early stage with limited number of apps (e.g. only web app and Smoothie) that we can reject new proofs if fields are missing because of "old" code, why not, fair enough.
In the same spirit, we shouldn't populate currency for product prices as it is redundant (if we're lucky) or incoherent.

**Comment by monsieurtanuki** [comment]
@raphodn Fair enough, but the current Smoothie users (beta only?) won't be able to add prices while the code isn't changed / merged for Smoothie.
And for the record the code in dart hasn't even been reviewed yet.

**Comment by raphodn** [comment]
As long as the price have a location/date/currency (which is the case in the mobile's current version) then we'll be able to retro-actively populate the linked proof location/date/currency fields (with a quick script).

**Comment by monsieurtanuki** [comment]
> As long as the price have a location/date/currency (which is the case in the mobile's current version)

Perhaps it would be a good idea to keep those parameters anyway at the price level (what would a price of `1` mean?) and to use them to check the consistency with the proof (and reject inconsistent proof and price parameters).

**Comment by raphodn** [comment]
Yes for now there's no plan to remove the price location/date/currency fields 😇
