### ISSUE TITLE
Sending null from the SDK?

### ISSUE THREAD

**Issue by CharlesNepote** [openfoodfacts/openfoodfacts-dart#944]
Copy/pasting a discussion with a user of the dart package:
Me:
1. about the energy: you should not add a computed value for energy, for many reasons: depending on the countries, energy is not computed the same way (between 4.2 and 4.4 kJ per kcal); in some countries (eg. the USA :wink:)  products only use calories (we do compute kJ when kCal are entered, but  it should be the decision of each player; we provide computed energy through the API as an independent field energy_100g)
2. if you enter a new value for kCal and the user has not entered a value for kJ, you should reset the value of kJ (because this one is now probably false)
(edited)

Them: "For 1 & 2, how should we go about resetting kJ? From the data quality report it seemed like our prior approach of not including kJ in the payload does not reset it. Does sending an explicit null in the dart SDK reset it?"

**Comment by monsieurtanuki** [comment]
@CharlesNepote In the dart code we don't compute anything related to nutrients, like energy or sodium.

We can unset a nutrient value by setting explicitly a `null` value.
I've just managed to
* reset both kcal and kj (100g) by setting both of them to `null` (`nutriments.setValue(Nutrient.energyKJ, perSize, null);`)
* then set kcal to `1` (now on the server, kcal=1, kj=null)
* then set kj to `1` (now on the server, kcal=1, kj=1)

Don't know if that answers all your questions.
