### ISSUE TITLE
URL helper for the product page

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-dart#952]
From a developer on the slack:
```
Jonah
Does the Dart / Flutter Sdk actually have a function to open the OFF product page directly or do I have to create the link myself?
1 reply

Edouard Marquez
  3 hours ago
No there is no such method, but it’s really simple to create:
https://world.openfoodfacts.org/product/7622210449283
```

Note: this could help for OdBL compliance, or for sharing a link to the product.

**Comment by monsieurtanuki** [comment]
Should be localized with country and (optional) language, as 
* https://be-it.openfoodfacts.org/product/7622210449283 gets redirected to https://be-it.openfoodfacts.org/product/7622210449283/prince-chocolat-biscuits-au-ble-complet-lu
* https://es.openfoodfacts.org/product/7622210449283 gets redirected to https://es.openfoodfacts.org/producto/7622210449283/prince-chocolate-lu

**Comment by monsieurtanuki** [comment]
Closed as already available as `OpenFoodAPIClient.getProductUri`: 
```dart
static Uri getProductUri(
    final String barcode, {
    final OpenFoodFactsLanguage? language,
    final OpenFoodFactsCountry? country,
    final UriProductHelper uriHelper = uriHelperFoodProd,
    required final bool replaceSubdomain,
  })
```
