### ISSUE TITLE
Add a "flavor"/"server type" to products

### ISSUE THREAD

**Issue by monsieurtanuki** [openfoodfacts/openfoodfacts-dart#972]
### Why - Problem description
In order to manage off, obf, opf and opff at the same time, we need some additional data.
Each product, each barcode should be associated with a _flavor_.

### What - Proposed solution
Make flavor a new product field.
That flavor may be provided by the server in a near future, but regardless, we get it from the server we're extracting the data from:
* a URL is used for product search
* from this URL (e.g. `world.openbeautyfacts.org`) we get a flavor (e.g. `obf`)
* we download related product data
* for each product data we download, we populate the flavor product field
* some day, when the server is ready, it can populate itself the flavor product field

### Additional questions
* We already have `Flavor` (`off`, `obf`, `opf`, `opff` and `off-pro`) for Prices and `ServerType` (`off`, `obf`, `opf` and `opff`) for Robotoff.
Which one should we use for our `Product`s? Or should we just stick to a mere `String` for more flexibility?
* As the field is supposed to be populated directly by the server in the future, what json tag would it be? `flavor`, `source`?

cf. https://github.com/openfoodfacts/smooth-app/issues/4540

**Comment by monsieurtanuki** [comment]
> * We already have `Flavor` (`off`, `obf`, `opf`, `opff` and `off-pro`) for Prices and `ServerType` (`off`, `obf`, `opf` and `opff`) for Robotoff.
>   Which one should we use for our `Product`s? Or should we just stick to a mere `String` for more flexibility?
> * As the field is supposed to be populated directly by the server in the future, what json tag would it be? `flavor`, `source`?

@teolemon Those are blocking questions. Any answer would help solve the issue, and tons of related issues in Smoothie.

**Comment by stephanegigandet** [comment]
@monsieurtanuki please use the "product_type" field instead, with values "food", "beauty", "petfood" and "product". This is the field that will be added in the OFF database and API.

**Comment by stephanegigandet** [comment]
flavors may go away, it's better to use product_type

**Comment by raphodn** [comment]
Ok good to know, in https://github.com/openfoodfacts/open-prices I store it under `Product.source`.

Also to note that we should update https://github.com/openfoodfacts/openfoodfacts-python/blob/8d1013a01c8fa674c1c84fd1729b73c621b5edd3/openfoodfacts/types.py#L11 and also store/return these values (food, beauty, petfood, product) somehow :)

**Comment by teolemon** [comment]
- Server side issue: https://github.com/openfoodfacts/openfoodfacts-server/issues/1174
