### ISSUE TITLE
New web folder structure for images

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-dart#983]
@monsieurtanuki @teolemon 

the server still support the old paths, but yes we should update the logic in the  Dart package.

>   /// * `12345678` for barcode `12345678`
>   /// * `123/456/789` for barcode `123456789`

> That will impact only the EAN8, of course.

Also others, e.g. 9 digit 123456789 is now in 000/012/345/6789. We not only split the EAN8, when we compute paths, we pad all codes with 0s so that they have 13 digits.

_Originally posted by @stephanegigandet in https://github.com/openfoodfacts/openfoodfacts-infrastructure/issues/363#issuecomment-2399794707_

**Comment by monsieurtanuki** [comment]
@teolemon already coded in #984, ready for review.
