### ISSUE TITLE
Support the universal scan API

### ISSUE THREAD

**Issue by g123k** [openfoodfacts/openfoodfacts-dart#995]
> The new API for getting products of all types is live, documentation is at: https://openfoodfacts.github.io/openfoodfacts-server/api/ref-v2/#get-/api/v2/product/-barcode-
> 
> If you query the OFF server and the product is not food, you will get a 302 redirect to OBF, OPF or OPFF, and you can use the product_type field to now what it is. 

 _Originally posted by @stephanegigandet in [#5855](https://github.com/openfoodfacts/smooth-app/issues/5855#issuecomment-2490474272)_

**Comment by teolemon** [comment]
@monsieurtanuki would you take this one to unlock next week's release ?

**Comment by monsieurtanuki** [comment]
> [@monsieurtanuki](https://github.com/monsieurtanuki) would you take this one to unlock next week's release ?

I'm not sure it's safe to expect the current issue to be 100% bullet-proof solved within 3 days, given the importance of "get product" within the app.

Besides, there are some problematic things in https://openfoodfacts.github.io/openfoodfacts-server/api/ref-v2/#get-/api/v2/product/-barcode-:
* missing parameters, like "lc", "tags_lc", "cc", "app_name", "app_version", "app_uuid", "app_platform" and "comment"
* same product json structure? not sure, to be double-checked (for instance it's not the same product structure in elastic search)
* we currently only use get product v3 (GET) in Smoothie, in this case we'd be going back to v2 (GET) from v2 (POST), which is getting a bit confusing

Given that OxF is being temporarily hidden in the [roadmap](https://github.com/openfoodfacts/smooth-app/discussions/5853), I would suggest not to focus on a dangerous and temporarily useless issue.

**Comment by teolemon** [comment]
What is being hidden about Open Everything Facts is the search only. 
The rationale being that 
- universal product addition needs to be shipped ASAP for quality reasons + db growth
- Scan for the same reason + pleasant unexpected surprise if they scan cosmetics 
- Search, on the hand, is US raising expectations, on something we won't be able to deliver (a lot of results, value added inside these results ..)


Also we need to ship the app, and the 4 query system is not sustainable for the server. We really need to go down to one query. 

I'm not really anxious about incompatibilities since it has been working on my phone for several weeks. The data model is really pretty much the same.

**Comment by monsieurtanuki** [comment]
> What is being hidden about Open Everything Facts is the search only. The rationale being that
> * universal product addition needs to be shipped ASAP for quality reasons + db growth

It's already implemented in Smoothie, isn't it?

> * Scan for the same reason + pleasant unexpected surprise if they scan cosmetics

It's already implemented in Smoothie, isn't it?

> * Search, on the hand, is US raising expectations, on something we won't be able to deliver (a lot of results, value added inside these results ..)

> Also we need to ship the app, and the 4 query system is not sustainable for the server. We really need to go down to one query.

That's the main point of your message. That I can understand: it's not sustainable to run 4 queries, one by server.

> I'm not really anxious about incompatibilities since it has been working on my phone for several weeks. The data model is really pretty much the same.

You mean, products from different OxFs, right? Fair enough. I meant product structure from the "new" get product compared to the current get product.

For the record we had a debilitating bug (https://github.com/openfoodfacts/smooth-app/issues/5864) that prevented us from saving product details during a whole week and caused [80k+ Sentry messages in one week](https://openfoodfacts.sentry.io/issues/4723294961/?notification_uuid=328dc112-6d45-4d45-9e7d-2f15f85be6bb&project=5376745&referrer=weekly_report). Not that much caused it, just product_type being eventually implemented on the server side and product_type being populated (or not) when saving product details.
So last minute apparently minor changes can have big impacts.

Still, you've ignored my comments about missing parameters, and the fact that everything (including Smoothie) should be ready within 3 days.

That said, I can implement an additional getOxfProduct method.
That'll give us flexibility in Smoothie.

**Comment by teolemon** [comment]
Ah, ok about v2/v3. @stephanegigandet will have a more accurate answer than me on this. 
I thought we were using v2 for product retrieval.

**Comment by monsieurtanuki** [comment]
Maybe using https://[openfoodfacts.github.io/openfoodfacts-server/api/ref-v3/#get-/api/v3/product/-barcode-](https://openfoodfacts.github.io/openfoodfacts-server/api/ref-v3/#get-/api/v3/product/-barcode-) instead would do the trick?

**Comment by monsieurtanuki** [comment]
@stephanegigandet @teolemon Looks like the redirection needs to be fine-tuned.

https://world.openfoodfacts.org/api/v3/product/3600551054476/?lc=en&tags_lc=en&fields=code%2Cproduct_type&product_type=all&app_name=off-dart+integration+tests

redirected to

https://[world.openbeautyfacts.orgapi](https://world.openbeautyfacts.orgapi/v3/product/3600551054476/?lc=en&tags_lc=en&fields=code%2Cproduct_type&product_type=all&app_name=off-dart+integration+tests)/v3/product/3600551054476/?lc=en&tags_lc=en&fields=code%2Cproduct_type&product_type=all&app_name=off-dart+integration+tests

![Image](https://github.com/user-attachments/assets/8fe3eb0e-690d-4f50-8bc0-f2c356272435)

**Comment by monsieurtanuki** [comment]
Haven't tested with v2.
In Smoothie we use only v3.

**Comment by stephanegigandet** [comment]
@monsieurtanuki:
- the new API to get products from any flavor  works for both v2 and v3 
- redirect to https://world.openbeautyfacts.orgapi -> good catch, I will fix it right away
- missing parameters, like "lc", "tags_lc", "cc", "app_name", "app_version", "app_uuid", "app_platform" and "comment"
The new API adds product_type, but everything else still work the same, including all those parameters.
- same product json structure? not sure, to be double-checked (for instance it's not the same product structure in elastic search)
It's the same product json structure, the only thing I changed was the support of product_type

**Comment by monsieurtanuki** [comment]
Thank you @stephanegigandet! Please ping me when the redirection missing / bug is fixed.

**Comment by teolemon** [comment]
@monsieurtanuki the pr by @stephanegigandet is available on . net ( there might be deployment issues cc @alexgarel )
https://github.com/openfoodfacts/openfoodfacts-server/pull/11056

**Comment by monsieurtanuki** [comment]
I'm not sure what I could test in .net, redirection-wise, as https://world.openbeautyfacts.net/, https://world.openpetfoodfacts.net/ and https://world.openproductsfacts.net/ do not exist.

That said, if that can help I did try https://world.openfoodfacts.net/api/v3/product/3600551054476/?lc=en&tags_lc=en&fields=code%2Cproduct_type&product_type=all&app_name=off-dart+integration+tests:
* product found
* status code = 200 (not expected)
* data without product_type (not expected)

**Comment by monsieurtanuki** [comment]
Thank you @stephanegigandet

There's still the "/" problem with the "products" server no correctly redirecting V3 queries:
* to "beauty": https://world.openproductsfacts.org/api/v3/product/3600551054476/?lc=en&tags_lc=en&fields=code%2Cproduct_type&product_type=all&app_name=off-dart+integration+tests
* to "pet food": https://world.openproductsfacts.org/api/v3/product/3564700266809/?lc=en&tags_lc=en&fields=code%2Cproduct_type&product_type=all&app_name=off-dart+integration+tests
* to "food": https://world.openproductsfacts.org/api/v3/product/7300400481588/?lc=en&tags_lc=en&fields=code%2Cproduct_type&product_type=all&app_name=off-dart+integration+tests

For V2 queries, unfortunately we land on that kind of pages (could be a "POST" side-effect):
```html
 <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>302 Found</title>
</head><body>
<h1>Found</h1>
<p>The document has moved <a href="https://world.openbeautyfacts.org/api/v2/product/3600551054476/">here</a>.</p>
<hr>
<address>Apache/2.4.61 (Debian) Server at world.openpetfoodfacts.org Port 80</address>
</body></html>
```

And even sometimes with still the "/" typo (on "products" server):
```html
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>302 Found</title>
</head><body>
<h1>Found</h1>
<p>The document has moved <a href="https://world.openbeautyfacts.orgapi/v2/product/3600551054476/">here</a>.</p>
<hr>
<address>Apache/2.4.61 (Debian) Server at world.openproductsfacts.org Port 80</address>
</body></html>
```

For the record we don't use get product V2 in Smoothie. We used to when the OxF servers didn't support the V3, which doesn't seem to be the case anymore.

**Comment by stephanegigandet** [comment]
@monsieurtanuki I probably made a mistake when deploying on Open Products Facts, it is fixed.

**Comment by monsieurtanuki** [comment]
> [@monsieurtanuki](https://github.com/monsieurtanuki) I probably made a mistake when deploying on Open Products Facts, it is fixed.

Now it works in all cases for V3!

But it still doesn't work for V2, probably because redirecting a POST isn't the same.

Solutions:
* a 307 redirection instead?
* just acknowledge the fact that the redirection for V2 doesn't work

@stephanegigandet Any suggestion?

**Comment by stephanegigandet** [comment]
Redirection for V2 READ requests works only if you use GET requests. I can try sending a 307 if the request was a POST.

**Comment by monsieurtanuki** [comment]
@stephanegigandet I've just tested with V2 in GET instead of POST, and the redirections do work!
Looks like we're POST'ing get product V2 since 2.5 years, cf. #414.

I can switch the off-dart "get product V2" from POST to GET. And I can deprecate it as well, as all OxF servers seem to support the "get product V3" syntax.

Is that OK with you?

**Comment by stephanegigandet** [comment]
If the app is not using v2 READ requests, then there's probably not much point to change it, you could just deprecate it.
